#![cfg(feature = "signing")]

//! Hash-linked log (spec/hushspec-log.md): the chained sink, rotation,
//! signing, verification, and the normative vectors under `fixtures/log/`.
//!
//! The vectors are generated by this file under fixed inputs; set
//! `HUSHSPEC_UPDATE_LOG_VECTORS=1` to regenerate them after a deliberate
//! change. The test otherwise checks that every `valid/` file verifies and
//! every `invalid/` file is rejected at the line its name implies.

use std::fs;
use std::path::{Path, PathBuf};

use chrono::{TimeZone, Utc};
use hushspec::log::{
    ChainedFileSink, GENESIS_HASH, LogEntry, LogVerifyOptions, Payload, PolicyEvent,
    PolicyEventKind, SdkInfo, verify_log, verify_log_files, verify_logs,
};
use hushspec::receipt::{
    Actor, AuditConfig, AuditContext, EnforcementMode, TimeSource, deterministic_uuid_v7,
    evaluate_audited, policy_summary,
};
use hushspec::signing::{Keyring, VerifyOptions, load_private_key};
use hushspec::sink::ReceiptSink;
use hushspec::{EvaluationAction, HushSpec, Resolution};

const CLOCK_MILLIS: u64 = 1_789_473_600_000; // 2026-09-15T12:00:00.000Z

fn repo_root() -> PathBuf {
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../..")).to_path_buf()
}

fn clock() -> chrono::DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 9, 15, 12, 0, 0).unwrap()
}

fn resolution() -> Resolution {
    let spec = HushSpec::parse(hushspec::load_builtin("default").unwrap()).unwrap();
    Resolution::from_resolved(&spec, Some("builtin:default")).unwrap()
}

fn ctx(index: u64) -> AuditContext {
    AuditContext {
        actor: Some(Actor {
            agent_id: Some("fixture-agent".to_string()),
            session_id: Some("fixture-session".to_string()),
            principal: Some("fixture@hushspec.dev".to_string()),
            runtime: Some("hushspec-conformance/0.2".to_string()),
        }),
        time_source: TimeSource::Trusted,
        clock: Some(clock()),
        receipt_id: Some(deterministic_uuid_v7(CLOCK_MILLIS, index)),
        ..AuditContext::default()
    }
}

fn config() -> AuditConfig {
    AuditConfig {
        enabled: true,
        include_rule_trace: true,
        record_duration: false,
    }
}

fn loaded_event(resolution: &Resolution) -> PolicyEvent {
    PolicyEvent {
        event: PolicyEventKind::Loaded,
        timestamp: "2026-09-15T12:00:00.000Z".to_string(),
        policy: policy_summary(resolution),
        enforcement_mode: EnforcementMode::Enforce,
        sdk: SdkInfo {
            name: "hushspec-conformance".to_string(),
            version: "0.2".to_string(),
        },
        spec_version: "0.2.0".to_string(),
        previous_content_hash: None,
    }
}

fn actions() -> Vec<EvaluationAction> {
    [
        serde_json::json!({"type": "tool_call", "target": "read_file"}),
        serde_json::json!({"type": "egress", "target": "api.github.com"}),
        serde_json::json!({"type": "file_read", "target": "/home/me/.ssh/id_rsa"}),
    ]
    .into_iter()
    .map(|v| serde_json::from_value(v).unwrap())
    .collect()
}

fn test_key() -> hushspec::signing::SigningKey {
    load_private_key(&repo_root().join("fixtures/signing/keys/test-signing.key.pem")).unwrap()
}

fn test_keyring() -> Keyring {
    Keyring::load(&repo_root().join("fixtures/signing/keys/keyring.json")).unwrap()
}

fn verify_options() -> VerifyOptions {
    VerifyOptions {
        now: clock(),
        max_clock_skew_seconds: 300,
        last_seen_version: None,
    }
}

fn temp_dir(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("hushspec-log-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

/// Write a chain of policy_loaded + three receipts into `path`.
fn write_basic(path: &Path, signed: bool) -> ChainedFileSink {
    let resolution = resolution();
    let mut sink = ChainedFileSink::open(path).unwrap().with_clock(clock());
    if signed {
        sink = sink.with_signer(test_key());
    }
    sink.record_policy_event(&loaded_event(&resolution))
        .unwrap();
    for (index, action) in actions().iter().enumerate() {
        let receipt = evaluate_audited(&resolution, action, &config(), &ctx(index as u64));
        sink.send(&receipt).unwrap();
    }
    sink
}

// ---------------------------------------------------------------- behavior --

#[test]
fn entries_link_and_verify() {
    let dir = temp_dir("basic");
    let path = dir.join("log.jsonl");
    let sink = write_basic(&path, false);
    assert_eq!(sink.head().0, 4);

    let text = fs::read_to_string(&path).unwrap();
    let entries: Vec<LogEntry> = text
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();
    assert_eq!(entries.len(), 4);
    assert_eq!(entries[0].seq, 1);
    assert_eq!(entries[0].prev_hash, GENESIS_HASH);
    assert!(entries[0].policy_event.is_some());
    for window in entries.windows(2) {
        assert_eq!(window[1].prev_hash, window[0].entry_hash);
        assert_eq!(window[1].seq, window[0].seq + 1);
    }
    for entry in &entries {
        assert_eq!(entry.compute_entry_hash().unwrap(), entry.entry_hash);
    }

    let report = verify_log("log.jsonl", &text, &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 4);
    assert_eq!(report.receipts, 3);
    assert_eq!(report.policy_events, 1);
    assert_eq!(report.last_seq, 4);
    assert_eq!(report.last_entry_hash, entries[3].entry_hash);
}

#[test]
fn reopening_continues_the_chain() {
    let dir = temp_dir("reopen");
    let path = dir.join("log.jsonl");
    let first = write_basic(&path, false);
    let head = first.head();
    drop(first);
    let sink = ChainedFileSink::open(&path).unwrap();
    assert_eq!(sink.head(), head);
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[0],
        &config(),
        &ctx(9),
    ))
    .unwrap();
    let text = fs::read_to_string(&path).unwrap();
    let report = verify_log("log.jsonl", &text, &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 5);
}

#[test]
fn signed_entries_verify_with_the_keyring_and_fail_without() {
    let dir = temp_dir("signed");
    let path = dir.join("log.jsonl");
    write_basic(&path, true);
    let text = fs::read_to_string(&path).unwrap();

    let options = LogVerifyOptions {
        require_signatures: true,
        keyring: Some(test_keyring()),
        verify: Some(verify_options()),
    };
    let report = verify_log("log.jsonl", &text, &options).unwrap();
    assert_eq!(report.signed, 4);
    assert_eq!(report.verified_signatures, 4);

    let no_keyring = LogVerifyOptions {
        require_signatures: true,
        keyring: None,
        verify: None,
    };
    let error = verify_log("log.jsonl", &text, &no_keyring).unwrap_err();
    assert!(error.message.contains("no_keyring"), "{error}");

    let untrusted = LogVerifyOptions {
        require_signatures: true,
        keyring: Some(
            Keyring::load(&repo_root().join("fixtures/signing/keys/keyring-revoked.json")).unwrap(),
        ),
        verify: Some(verify_options()),
    };
    let error = verify_log("log.jsonl", &text, &untrusted).unwrap_err();
    assert_eq!(error.line, 1);
    assert!(error.message.contains("signature"), "{error}");
}

#[test]
fn unsigned_entries_fail_when_signatures_are_required() {
    let dir = temp_dir("unsigned");
    let path = dir.join("log.jsonl");
    write_basic(&path, false);
    let text = fs::read_to_string(&path).unwrap();
    let options = LogVerifyOptions {
        require_signatures: true,
        keyring: Some(test_keyring()),
        verify: Some(verify_options()),
    };
    let error = verify_log("log.jsonl", &text, &options).unwrap_err();
    assert_eq!(error.line, 1);
    assert!(error.message.contains("entry_unsigned"), "{error}");
}

#[test]
fn rotation_carries_the_chain_into_the_next_file() {
    let dir = temp_dir("rotate");
    let first = dir.join("log-1.jsonl");
    let second = dir.join("log-2.jsonl");
    let sink = write_basic(&first, false);
    let last_hash = sink.head().1;
    let started = sink.rotate(&second).unwrap();
    assert_eq!(started.seq, 1);
    assert_eq!(started.prev_hash, last_hash);
    assert_eq!(
        started
            .log_started
            .as_ref()
            .unwrap()
            .previous_entry_hash
            .as_deref(),
        Some(last_hash.as_str())
    );
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[1],
        &config(),
        &ctx(7),
    ))
    .unwrap();

    let report = verify_log_files(&[&first, &second], &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.files, 2);
    assert_eq!(report.entries, 6);

    // The second file alone verifies from its log_started link.
    let text = fs::read_to_string(&second).unwrap();
    let alone = verify_log("log-2.jsonl", &text, &LogVerifyOptions::default()).unwrap();
    assert_eq!(alone.entries, 2);

    // Given out of order, the link breaks.
    let error = verify_log_files(&[&second, &first], &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 1);
}

#[test]
fn tampering_is_detected_at_the_first_broken_line() {
    let dir = temp_dir("tamper");
    let path = dir.join("log.jsonl");
    write_basic(&path, false);
    let text = fs::read_to_string(&path).unwrap();
    let lines: Vec<&str> = text.lines().collect();

    // Edit a receipt field in line 3.
    let edited = lines[2].replacen("\"allow\"", "\"deny\"", 1);
    let tampered = [lines[0], lines[1], &edited, lines[3]].join("\n");
    let error = verify_log("t", &tampered, &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 3);
    assert!(error.message.contains("entry_hash"), "{error}");

    // Delete line 2.
    let deleted = [lines[0], lines[2], lines[3]].join("\n");
    let error = verify_log("t", &deleted, &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 2);
    assert!(error.message.contains("sequence gap"), "{error}");

    // Reorder lines 2 and 3.
    let reordered = [lines[0], lines[2], lines[1], lines[3]].join("\n");
    let error = verify_log("t", &reordered, &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 2);

    // Truncation is not detectable from the file alone (log spec 9).
    let truncated = [lines[0], lines[1]].join("\n");
    assert!(verify_log("t", &truncated, &LogVerifyOptions::default()).is_ok());
}

#[test]
fn payload_must_match_entry_type() {
    let dir = temp_dir("payload");
    let path = dir.join("log.jsonl");
    let sink = write_basic(&path, false);
    let entry = sink
        .append(Payload::PolicyEvent(Box::new(loaded_event(&resolution()))))
        .unwrap();
    let mut value = serde_json::to_value(&entry).unwrap();
    value["entry_type"] = serde_json::json!("receipt");
    let text = fs::read_to_string(&path).unwrap();
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    lines.pop();
    lines.push(value.to_string());
    let error = verify_log("t", &lines.join("\n"), &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 5);
    assert!(error.message.contains("payload"), "{error}");
}

// ----------------------------------------------------------------- vectors --

fn vectors_dir() -> PathBuf {
    repo_root().join("fixtures/log")
}

/// Build every vector into `out` (a temp dir) as `(relative name, text)`.
fn generate_vectors() -> Vec<(String, String)> {
    let dir = temp_dir("vectors");
    let mut files = Vec::new();

    let basic = dir.join("basic.jsonl");
    write_basic(&basic, false);
    let basic_text = fs::read_to_string(&basic).unwrap();
    files.push(("valid/basic.jsonl".to_string(), basic_text.clone()));

    let signed = dir.join("signed.jsonl");
    write_basic(&signed, true);
    let signed_text = fs::read_to_string(&signed).unwrap();
    files.push(("valid/signed.jsonl".to_string(), signed_text.clone()));

    let rotated_1 = dir.join("rotated-1.jsonl");
    let rotated_2 = dir.join("rotated-2.jsonl");
    let sink = write_basic(&rotated_1, false);
    sink.rotate(&rotated_2).unwrap();
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[1],
        &config(),
        &ctx(7),
    ))
    .unwrap();
    files.push((
        "valid/rotated-1.jsonl".to_string(),
        fs::read_to_string(&rotated_1).unwrap(),
    ));
    files.push((
        "valid/rotated-2.jsonl".to_string(),
        fs::read_to_string(&rotated_2).unwrap(),
    ));

    let lines: Vec<&str> = basic_text.lines().collect();
    files.push((
        "invalid/tampered-line-3.jsonl".to_string(),
        [
            lines[0],
            lines[1],
            &lines[2].replacen("\"allow\"", "\"deny\"", 1),
            lines[3],
        ]
        .join("\n")
            + "\n",
    ));
    files.push((
        "invalid/deleted-line-2.jsonl".to_string(),
        [lines[0], lines[2], lines[3]].join("\n") + "\n",
    ));
    files.push((
        "invalid/reordered-line-2.jsonl".to_string(),
        [lines[0], lines[2], lines[1], lines[3]].join("\n") + "\n",
    ));
    let mut bad_prev: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
    bad_prev["prev_hash"] = serde_json::json!(GENESIS_HASH);
    files.push((
        "invalid/bad-prev-hash-line-2.jsonl".to_string(),
        [lines[0], &bad_prev.to_string(), lines[2], lines[3]].join("\n") + "\n",
    ));
    let signed_lines: Vec<&str> = signed_text.lines().collect();
    let mut bad_sig: serde_json::Value = serde_json::from_str(signed_lines[3]).unwrap();
    let sig = bad_sig["signature"]["signature"]
        .as_str()
        .unwrap()
        .to_string();
    let flipped = match sig.strip_prefix('A') {
        Some(rest) => format!("B{rest}"),
        None => format!("A{}", sig.get(1..).unwrap_or("")),
    };
    bad_sig["signature"]["signature"] = serde_json::json!(flipped);
    files.push((
        "invalid/bad-signature-line-4.jsonl".to_string(),
        [
            signed_lines[0],
            signed_lines[1],
            signed_lines[2],
            &bad_sig.to_string(),
        ]
        .join("\n")
            + "\n",
    ));
    let _ = fs::remove_dir_all(&dir);
    files
}

fn expected_break_line(name: &str) -> usize {
    name.rsplit('-')
        .next()
        .and_then(|tail| tail.trim_end_matches(".jsonl").parse().ok())
        .unwrap_or_else(|| panic!("{name}: file name must end with the breaking line number"))
}

#[test]
fn log_vectors_are_current_and_behave() {
    let update = std::env::var("HUSHSPEC_UPDATE_LOG_VECTORS").is_ok();
    let generated = generate_vectors();
    if update {
        for (name, text) in &generated {
            let path = vectors_dir().join(name);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(&path, text).unwrap();
        }
    }
    let mut drift = Vec::new();
    for (name, text) in &generated {
        let path = vectors_dir().join(name);
        match fs::read_to_string(&path) {
            Ok(existing) if &existing == text => {}
            Ok(_) => drift.push(format!("{name} differs")),
            Err(_) => drift.push(format!("{name} is missing")),
        }
    }
    assert!(
        drift.is_empty(),
        "log vectors drifted (run with HUSHSPEC_UPDATE_LOG_VECTORS=1 after a deliberate change):\n{}",
        drift.join("\n")
    );

    // Behaviour of the committed files.
    let signed_options = LogVerifyOptions {
        require_signatures: false,
        keyring: Some(test_keyring()),
        verify: Some(verify_options()),
    };
    for name in ["valid/basic.jsonl", "valid/signed.jsonl"] {
        let text = fs::read_to_string(vectors_dir().join(name)).unwrap();
        verify_log(name, &text, &signed_options)
            .unwrap_or_else(|e| panic!("{name} must verify: {e}"));
    }
    let first = fs::read_to_string(vectors_dir().join("valid/rotated-1.jsonl")).unwrap();
    let second = fs::read_to_string(vectors_dir().join("valid/rotated-2.jsonl")).unwrap();
    verify_logs(
        &[("rotated-1", &first), ("rotated-2", &second)],
        &LogVerifyOptions::default(),
    )
    .expect("rotated pair verifies");

    let invalid_dir = vectors_dir().join("invalid");
    let mut count = 0;
    for entry in fs::read_dir(&invalid_dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let text = fs::read_to_string(&path).unwrap();
        let error = verify_log(&name, &text, &signed_options)
            .expect_err(&format!("{name} must be rejected"));
        assert_eq!(error.line, expected_break_line(&name), "{name}: {error}");
        count += 1;
    }
    assert!(
        count >= 5,
        "expected at least 5 invalid vectors, found {count}"
    );
}
