#![cfg(feature = "signing")]

//! Hash-linked log (spec/hushspec-log.md): the chained sink, rotation,
//! signing, verification, and the normative vectors under `fixtures/log/`.
//!
//! The vectors are generated by this file under fixed inputs; set
//! `HUSHSPEC_UPDATE_LOG_VECTORS=1` to regenerate them after a deliberate
//! change. The test otherwise checks that every `valid/` file verifies and
//! every `invalid/` file is rejected at the line its name implies.

use std::fs;
use std::path::{Path, PathBuf};

use chrono::{TimeZone, Utc};
use hushspec::log::{
    ChainedFileSink, GENESIS_HASH, LogEntry, LogVerifyOptions, Payload, PolicyEvent,
    PolicyEventKind, SdkInfo, verify_log, verify_log_files, verify_logs,
};
use hushspec::receipt::{
    Actor, AuditConfig, AuditContext, EnforcementMode, TimeSource, deterministic_uuid_v7,
    evaluate_audited, policy_summary,
};
use hushspec::signing::{Keyring, VerifyOptions, load_private_key};
use hushspec::sink::ReceiptSink;
use hushspec::{EvaluationAction, HushSpec, Resolution};

const CLOCK_MILLIS: u64 = 1_789_473_600_000; // 2026-09-15T12:00:00.000Z

#[test]
fn schema_derived_log_entries() {
    let vectors: serde_json::Value =
        serde_json::from_str(include_str!("../../../fixtures/log/schema-vectors.json")).unwrap();
    let schema: serde_json::Value = serde_json::from_str(include_str!(
        "../../../schemas/hushspec-log-entry.v1.schema.json"
    ))
    .unwrap();
    let validator = jsonschema::JSONSchema::options()
        .with_draft(jsonschema::Draft::Draft202012)
        .should_validate_formats(true)
        .compile(&schema)
        .unwrap();
    let mut failures = Vec::new();
    for vector in vectors.as_array().unwrap() {
        let entry = &vector["entry"];
        let valid = vector["valid"].as_bool().unwrap();
        let id = vector["id"].as_str().unwrap();
        assert_eq!(validator.is_valid(entry), valid, "schema oracle: {id}");
        let mut unsigned = entry.clone();
        unsigned.as_object_mut().unwrap().remove("entry_hash");
        unsigned.as_object_mut().unwrap().remove("signature");
        let canonical = hushspec::canonical::serialize_jcs(&unsigned).unwrap();
        assert_eq!(
            hushspec::canonical::digest(&canonical),
            entry["entry_hash"],
            "hash: {id}"
        );
        let result = verify_log(id, &entry.to_string(), &LogVerifyOptions::default());
        if result.is_ok() != valid {
            failures.push(format!("{id}: {result:?}"));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

fn repo_root() -> PathBuf {
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../..")).to_path_buf()
}

fn clock() -> chrono::DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 9, 15, 12, 0, 0).unwrap()
}

fn resolution() -> Resolution {
    let spec = HushSpec::parse(hushspec::load_builtin("default").unwrap()).unwrap();
    Resolution::from_resolved(&spec, Some("builtin:default")).unwrap()
}

fn ctx(index: u64) -> AuditContext {
    AuditContext {
        actor: Some(Actor {
            agent_id: Some("fixture-agent".to_string()),
            session_id: Some("fixture-session".to_string()),
            principal: Some("fixture@hushspec.dev".to_string()),
            runtime: Some("hushspec-conformance/0.2".to_string()),
        }),
        time_source: TimeSource::Trusted,
        clock: Some(clock()),
        receipt_id: Some(deterministic_uuid_v7(CLOCK_MILLIS, index)),
        ..AuditContext::default()
    }
}

fn config() -> AuditConfig {
    AuditConfig {
        enabled: true,
        include_rule_trace: true,
        record_duration: false,
    }
}

fn loaded_event(resolution: &Resolution) -> PolicyEvent {
    PolicyEvent {
        event: PolicyEventKind::Loaded,
        timestamp: "2026-09-15T12:00:00.000Z".to_string(),
        policy: policy_summary(resolution),
        enforcement_mode: EnforcementMode::Enforce,
        sdk: SdkInfo {
            name: "hushspec-conformance".to_string(),
            version: "0.2".to_string(),
        },
        spec_version: "0.2.0".to_string(),
        previous_content_hash: None,
    }
}

fn actions() -> Vec<EvaluationAction> {
    [
        serde_json::json!({"type": "tool_call", "target": "read_file"}),
        serde_json::json!({"type": "egress", "target": "api.github.com"}),
        serde_json::json!({"type": "file_read", "target": "/home/me/.ssh/id_rsa"}),
    ]
    .into_iter()
    .map(|v| serde_json::from_value(v).unwrap())
    .collect()
}

fn test_key() -> hushspec::signing::SigningKey {
    load_private_key(&repo_root().join("fixtures/signing/keys/test-signing.key.pem")).unwrap()
}

fn test_keyring() -> Keyring {
    Keyring::load(&repo_root().join("fixtures/signing/keys/keyring.json")).unwrap()
}

fn verify_options() -> VerifyOptions {
    VerifyOptions {
        now: clock(),
        max_clock_skew_seconds: 300,
        last_seen_version: None,
    }
}

fn temp_dir(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("hushspec-log-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

/// Write a chain of policy_loaded + three receipts into `path`.
fn write_basic(path: &Path, signed: bool) -> ChainedFileSink {
    let resolution = resolution();
    let mut sink = ChainedFileSink::open(path).unwrap().with_clock(clock());
    if signed {
        sink = sink.with_signer(test_key());
    }
    sink.record_policy_event(&loaded_event(&resolution))
        .unwrap();
    for (index, action) in actions().iter().enumerate() {
        let receipt = evaluate_audited(&resolution, action, &config(), &ctx(index as u64));
        sink.send(&receipt).unwrap();
    }
    sink
}

// ---------------------------------------------------------------- behavior --

#[test]
fn entries_link_and_verify() {
    let dir = temp_dir("basic");
    let path = dir.join("log.jsonl");
    let sink = write_basic(&path, false);
    assert_eq!(sink.head().0, 4);

    let text = fs::read_to_string(&path).unwrap();
    let entries: Vec<LogEntry> = text
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();
    assert_eq!(entries.len(), 4);
    assert_eq!(entries[0].seq, 1);
    assert_eq!(entries[0].prev_hash, GENESIS_HASH);
    assert!(entries[0].policy_event.is_some());
    for window in entries.windows(2) {
        assert_eq!(window[1].prev_hash, window[0].entry_hash);
        assert_eq!(window[1].seq, window[0].seq + 1);
    }
    for entry in &entries {
        assert_eq!(entry.compute_entry_hash().unwrap(), entry.entry_hash);
    }

    let report = verify_log("log.jsonl", &text, &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 4);
    assert_eq!(report.receipts, 3);
    assert_eq!(report.policy_events, 1);
    assert_eq!(report.last_seq, 4);
    assert_eq!(report.last_entry_hash, entries[3].entry_hash);
}

#[test]
fn reopening_continues_the_chain() {
    let dir = temp_dir("reopen");
    let path = dir.join("log.jsonl");
    let first = write_basic(&path, false);
    let head = first.head();
    drop(first);
    let sink = ChainedFileSink::open(&path).unwrap();
    assert_eq!(sink.head(), head);
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[0],
        &config(),
        &ctx(9),
    ))
    .unwrap();
    let text = fs::read_to_string(&path).unwrap();
    let report = verify_log("log.jsonl", &text, &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 5);
}

#[test]
fn two_sinks_on_one_file_extend_one_chain() {
    let dir = temp_dir("two-sinks");
    let path = dir.join("log.jsonl");
    let resolution = resolution();
    let first = ChainedFileSink::open(&path).unwrap().with_clock(clock());
    let second = ChainedFileSink::open(&path).unwrap().with_clock(clock());

    first
        .record_policy_event(&loaded_event(&resolution))
        .unwrap();
    for (index, action) in actions().iter().enumerate() {
        let receipt = evaluate_audited(&resolution, action, &config(), &ctx(index as u64));
        let sink = if index % 2 == 0 { &second } else { &first };
        sink.send(&receipt).unwrap();
    }

    let text = fs::read_to_string(&path).unwrap();
    let entries: Vec<LogEntry> = text
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect();
    assert_eq!(
        entries.iter().map(|entry| entry.seq).collect::<Vec<_>>(),
        vec![1, 2, 3, 4]
    );
    let report = verify_log("log.jsonl", &text, &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 4);
    assert_eq!(report.last_seq, 4);
    assert_eq!(report.last_entry_hash, entries[3].entry_hash);
    assert_eq!(second.head(), (4, entries[3].entry_hash.clone()));
}

#[test]
fn signed_entries_verify_with_the_keyring_and_fail_without() {
    let dir = temp_dir("signed");
    let path = dir.join("log.jsonl");
    write_basic(&path, true);
    let text = fs::read_to_string(&path).unwrap();

    let options = LogVerifyOptions {
        require_signatures: true,
        keyring: Some(test_keyring()),
        verify: Some(verify_options()),
    };
    let report = verify_log("log.jsonl", &text, &options).unwrap();
    assert_eq!(report.signed, 4);
    assert_eq!(report.verified_signatures, 4);

    let no_keyring = LogVerifyOptions {
        require_signatures: true,
        keyring: None,
        verify: None,
    };
    let error = verify_log("log.jsonl", &text, &no_keyring).unwrap_err();
    assert!(error.message.contains("no_keyring"), "{error}");

    let untrusted = LogVerifyOptions {
        require_signatures: true,
        keyring: Some(
            Keyring::load(&repo_root().join("fixtures/signing/keys/keyring-revoked.json")).unwrap(),
        ),
        verify: Some(verify_options()),
    };
    let error = verify_log("log.jsonl", &text, &untrusted).unwrap_err();
    assert_eq!(error.line, 1);
    assert!(error.message.contains("signature"), "{error}");
}

#[test]
fn unsigned_entries_fail_when_signatures_are_required() {
    let dir = temp_dir("unsigned");
    let path = dir.join("log.jsonl");
    write_basic(&path, false);
    let text = fs::read_to_string(&path).unwrap();
    let options = LogVerifyOptions {
        require_signatures: true,
        keyring: Some(test_keyring()),
        verify: Some(verify_options()),
    };
    let error = verify_log("log.jsonl", &text, &options).unwrap_err();
    assert_eq!(error.line, 1);
    assert!(error.message.contains("entry_unsigned"), "{error}");
}

#[test]
fn rotation_carries_the_chain_into_the_next_file() {
    let dir = temp_dir("rotate");
    let first = dir.join("log-1.jsonl");
    let second = dir.join("log-2.jsonl");
    let sink = write_basic(&first, false);
    let last_hash = sink.head().1;
    let started = sink.rotate(&second).unwrap();
    assert_eq!(started.seq, 1);
    assert_eq!(started.prev_hash, last_hash);
    assert_eq!(
        started
            .log_started
            .as_ref()
            .unwrap()
            .previous_entry_hash
            .as_deref(),
        Some(last_hash.as_str())
    );
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[1],
        &config(),
        &ctx(7),
    ))
    .unwrap();

    let report = verify_log_files(&[&first, &second], &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.files, 2);
    assert_eq!(report.entries, 6);

    // The second file alone verifies from its log_started link.
    let text = fs::read_to_string(&second).unwrap();
    let alone = verify_log("log-2.jsonl", &text, &LogVerifyOptions::default()).unwrap();
    assert_eq!(alone.entries, 2);

    // Given out of order, the link breaks.
    let error = verify_log_files(&[&second, &first], &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 1);
}

#[test]
fn rotation_links_the_old_files_last_entry_as_it_is_on_disk() {
    let dir = temp_dir("rotate-shared");
    let first = dir.join("log-1.jsonl");
    let second = dir.join("log-2.jsonl");
    let resolution = resolution();
    let rotating = ChainedFileSink::open(&first).unwrap().with_clock(clock());
    let other = ChainedFileSink::open(&first).unwrap().with_clock(clock());
    rotating
        .record_policy_event(&loaded_event(&resolution))
        .unwrap();
    // The other writer extends the file after this sink last wrote to it.
    other
        .send(&evaluate_audited(
            &resolution,
            &actions()[0],
            &config(),
            &ctx(1),
        ))
        .unwrap();
    let on_disk = other.head().1;
    assert_ne!(rotating.head().1, on_disk);

    let started = rotating.rotate(&second).unwrap();
    assert_eq!(started.prev_hash, on_disk);
    assert_eq!(
        started
            .log_started
            .as_ref()
            .unwrap()
            .previous_entry_hash
            .as_deref(),
        Some(on_disk.as_str())
    );
    let report = verify_log_files(&[&first, &second], &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 3);
}

#[test]
fn a_chain_rotated_at_genesis_verifies() {
    let dir = temp_dir("rotate-genesis");
    let first = dir.join("log-1.jsonl");
    let second = dir.join("log-2.jsonl");
    // A writer that rotates before it has written anything carries the genesis
    // hash into the new file. The link is recorded all the same, so a verifier
    // given both files sees one chain.
    fs::write(&first, "").unwrap();
    let sink = ChainedFileSink::open(&first).unwrap().with_clock(clock());
    let started = sink.rotate(&second).unwrap();
    assert_eq!(started.prev_hash, GENESIS_HASH);
    assert_eq!(
        started
            .log_started
            .as_ref()
            .unwrap()
            .previous_entry_hash
            .as_deref(),
        Some(GENESIS_HASH)
    );
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[0],
        &config(),
        &ctx(0),
    ))
    .unwrap();

    let report = verify_log_files(&[&first, &second], &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.files, 2);
    assert_eq!(report.entries, 2);
}

#[test]
fn a_rotation_that_cannot_be_written_leaves_the_sink_on_the_old_file() {
    let dir = temp_dir("rotate-unwritable");
    let first = dir.join("log-1.jsonl");
    let sink = write_basic(&first, false);
    let head = sink.head();

    // A regular file where the new log's directory would be: the rotation
    // cannot create the file or its lock.
    let blocker = dir.join("not-a-directory");
    fs::write(&blocker, "").unwrap();
    let second = blocker.join("log-2.jsonl");
    sink.rotate(&second)
        .expect_err("the new file cannot be written");

    assert_eq!(sink.path(), first, "the sink still writes the old file");
    assert_eq!(sink.head(), head, "the chain head is unchanged");

    // The old file is still current, so the next receipt continues its chain.
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[0],
        &config(),
        &ctx(9),
    ))
    .unwrap();
    let report = verify_log_files(&[&first], &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 5);
}

#[test]
fn a_log_is_created_together_with_its_parent_directory() {
    let dir = temp_dir("missing-parent");
    let path = dir.join("logs").join("audit.jsonl");
    let sink = ChainedFileSink::open(&path).unwrap().with_clock(clock());
    sink.record_policy_event(&loaded_event(&resolution()))
        .unwrap();

    let report = verify_log_files(&[&path], &LogVerifyOptions::default()).unwrap();
    assert_eq!(report.entries, 1);
}

#[test]
fn tampering_is_detected_at_the_first_broken_line() {
    let dir = temp_dir("tamper");
    let path = dir.join("log.jsonl");
    write_basic(&path, false);
    let text = fs::read_to_string(&path).unwrap();
    let lines: Vec<&str> = text.lines().collect();

    // Edit a receipt field in line 3.
    let edited = lines[2].replacen("\"allow\"", "\"deny\"", 1);
    let tampered = [lines[0], lines[1], &edited, lines[3]].join("\n");
    let error = verify_log("t", &tampered, &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 3);
    assert!(error.message.contains("entry_hash"), "{error}");

    // Delete line 2.
    let deleted = [lines[0], lines[2], lines[3]].join("\n");
    let error = verify_log("t", &deleted, &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 2);
    assert!(error.message.contains("sequence gap"), "{error}");

    // Reorder lines 2 and 3.
    let reordered = [lines[0], lines[2], lines[1], lines[3]].join("\n");
    let error = verify_log("t", &reordered, &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 2);

    // Truncation is not detectable from the file alone (log spec 9).
    let truncated = [lines[0], lines[1]].join("\n");
    assert!(verify_log("t", &truncated, &LogVerifyOptions::default()).is_ok());
}

#[test]
fn payload_must_match_entry_type() {
    let dir = temp_dir("payload");
    let path = dir.join("log.jsonl");
    let sink = write_basic(&path, false);
    let entry = sink
        .append(Payload::PolicyEvent(Box::new(loaded_event(&resolution()))))
        .unwrap();
    let mut value = serde_json::to_value(&entry).unwrap();
    value["entry_type"] = serde_json::json!("receipt");
    let text = fs::read_to_string(&path).unwrap();
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    lines.pop();
    lines.push(value.to_string());
    let error = verify_log("t", &lines.join("\n"), &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 5);
    assert!(error.message.contains("payload"), "{error}");
}

#[test]
fn a_receipt_payload_must_validate_against_the_receipt_schema() {
    let dir = temp_dir("receipt-payload");
    let path = dir.join("log.jsonl");
    write_basic(&path, false);
    let text = fs::read_to_string(&path).unwrap();
    let lines: Vec<&str> = text.lines().collect();

    // The entry hash covers whatever JSON the line held, so each break has to
    // be reported by the receipt check rather than as a hash mismatch: edit
    // the receipt on line 2 and restore the entry hash over the result.
    let cases: [(&[&str], serde_json::Value, &str); 3] = [
        (
            &["receipt_id"],
            serde_json::json!("0198f0e0-1111-4111-8111-111111111111"),
            "receipt_id",
        ),
        (
            &["policy", "content_hash"],
            serde_json::json!("3".repeat(64)),
            "policy.content_hash",
        ),
        (
            &["rule_trace", "0", "rule_block"],
            serde_json::json!("rules.egress"),
            "rule_trace[0].rule_block",
        ),
    ];
    for (pointer, broken, expected) in cases {
        let mut value: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
        let mut target = &mut value["receipt"];
        for step in pointer {
            target = match step.parse::<usize>() {
                Ok(index) => &mut target[index],
                Err(_) => &mut target[*step],
            };
        }
        *target = broken;
        value["entry_hash"] = serde_json::json!(value_entry_hash(&value));
        let text = [lines[0], &value.to_string(), lines[2], lines[3]].join("\n");
        let error = verify_log("t", &text, &LogVerifyOptions::default()).unwrap_err();
        assert_eq!(error.line, 2);
        assert!(
            error
                .message
                .starts_with("receipt does not validate against the 0.2 receipt schema"),
            "{error}"
        );
        assert!(error.message.contains(expected), "{error}");
    }
}

#[test]
fn an_explicit_null_in_a_receipt_is_a_break() {
    let dir = temp_dir("receipt-null");
    let path = dir.join("log.jsonl");
    write_basic(&path, false);
    let text = fs::read_to_string(&path).unwrap();
    let lines: Vec<&str> = text.lines().collect();

    // An absent member and one set to `null` deserialize to the same receipt,
    // but they are not the same document and the entry hash covers both.
    let mut value: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
    value["receipt"]["reason"] = serde_json::Value::Null;
    value["entry_hash"] = serde_json::json!(value_entry_hash(&value));
    let text = [lines[0], &value.to_string(), lines[2], lines[3]].join("\n");
    let error = verify_log("t", &text, &LogVerifyOptions::default()).unwrap_err();
    assert_eq!(error.line, 2);
    assert!(error.message.contains("reason must not be null"), "{error}");
}

// ----------------------------------------------------------------- vectors --

fn vectors_dir() -> PathBuf {
    repo_root().join("fixtures/log")
}

/// Build every vector into `out` (a temp dir) as `(relative name, text)`.
fn generate_vectors() -> Vec<(String, String)> {
    let dir = temp_dir("vectors");
    let mut files = Vec::new();

    let basic = dir.join("basic.jsonl");
    write_basic(&basic, false);
    let basic_text = fs::read_to_string(&basic).unwrap();
    files.push(("valid/basic.jsonl".to_string(), basic_text.clone()));

    let signed = dir.join("signed.jsonl");
    write_basic(&signed, true);
    let signed_text = fs::read_to_string(&signed).unwrap();
    files.push(("valid/signed.jsonl".to_string(), signed_text.clone()));

    let rotated_1 = dir.join("rotated-1.jsonl");
    let rotated_2 = dir.join("rotated-2.jsonl");
    let sink = write_basic(&rotated_1, false);
    sink.rotate(&rotated_2).unwrap();
    sink.send(&evaluate_audited(
        &resolution(),
        &actions()[1],
        &config(),
        &ctx(7),
    ))
    .unwrap();
    files.push((
        "valid/rotated-1.jsonl".to_string(),
        fs::read_to_string(&rotated_1).unwrap(),
    ));
    files.push((
        "valid/rotated-2.jsonl".to_string(),
        fs::read_to_string(&rotated_2).unwrap(),
    ));

    let lines: Vec<&str> = basic_text.lines().collect();
    files.push((
        "invalid/tampered-line-3.jsonl".to_string(),
        [
            lines[0],
            lines[1],
            &lines[2].replacen("\"allow\"", "\"deny\"", 1),
            lines[3],
        ]
        .join("\n")
            + "\n",
    ));
    files.push((
        "invalid/deleted-line-2.jsonl".to_string(),
        [lines[0], lines[2], lines[3]].join("\n") + "\n",
    ));
    files.push((
        "invalid/reordered-line-2.jsonl".to_string(),
        [lines[0], lines[2], lines[1], lines[3]].join("\n") + "\n",
    ));
    let mut bad_prev: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
    bad_prev["prev_hash"] = serde_json::json!(GENESIS_HASH);
    files.push((
        "invalid/bad-prev-hash-line-2.jsonl".to_string(),
        [lines[0], &bad_prev.to_string(), lines[2], lines[3]].join("\n") + "\n",
    ));
    // A receipt payload that is not a 0.2 receipt, with the rest of the chain
    // relinked so line 2 is the first break (log spec 8, step 8) rather than
    // the hash check that a stale `prev_hash` would trip first.
    let mut relinked: Vec<serde_json::Value> = lines[1..]
        .iter()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect();
    relinked[0]["receipt"] = serde_json::json!({"receipt_version": "0.2"});
    for index in 0..relinked.len() {
        if index > 0 {
            let previous = relinked[index - 1]["entry_hash"].clone();
            relinked[index]["prev_hash"] = previous;
        }
        let hash = value_entry_hash(&relinked[index]);
        relinked[index]["entry_hash"] = serde_json::json!(hash);
    }
    let mut malformed_receipt = lines[0].to_string();
    for value in &relinked {
        malformed_receipt.push('\n');
        malformed_receipt.push_str(&value.to_string());
    }
    malformed_receipt.push('\n');
    files.push((
        "invalid/malformed-receipt-line-2.jsonl".to_string(),
        malformed_receipt,
    ));

    // Two payloads that are not the payloads the log-entry schema describes,
    // each in a chain relinked around it so the first break is the payload
    // (log spec 8, step 1) rather than a hash the edit invalidated.
    let mut empty_started = entries_of(&fs::read_to_string(&rotated_2).unwrap());
    empty_started[0]["log_started"] = serde_json::json!({});
    relink(&mut empty_started, GENESIS_HASH);
    files.push((
        "invalid/empty-log-started-line-1.jsonl".to_string(),
        json_lines(&empty_started),
    ));
    let mut without_sdk = entries_of(&basic_text);
    without_sdk[0]["policy_event"]
        .as_object_mut()
        .unwrap()
        .remove("sdk");
    relink(&mut without_sdk, GENESIS_HASH);
    files.push((
        "invalid/policy-event-without-sdk-line-1.jsonl".to_string(),
        json_lines(&without_sdk),
    ));

    let signed_lines: Vec<&str> = signed_text.lines().collect();
    let mut bad_sig: serde_json::Value = serde_json::from_str(signed_lines[3]).unwrap();
    let sig = bad_sig["signature"]["signature"]
        .as_str()
        .unwrap()
        .to_string();
    let flipped = match sig.strip_prefix('A') {
        Some(rest) => format!("B{rest}"),
        None => format!("A{}", sig.get(1..).unwrap_or("")),
    };
    bad_sig["signature"]["signature"] = serde_json::json!(flipped);
    files.push((
        "invalid/bad-signature-line-4.jsonl".to_string(),
        [
            signed_lines[0],
            signed_lines[1],
            signed_lines[2],
            &bad_sig.to_string(),
        ]
        .join("\n")
            + "\n",
    ));
    let _ = fs::remove_dir_all(&dir);
    files
}

/// The entries of a log file, as the raw JSON each line holds.
fn entries_of(text: &str) -> Vec<serde_json::Value> {
    text.lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect()
}

/// Relink `entries` onto `prev_hash`, restoring every `entry_hash` over the
/// entry that now carries it, so the only break a vector holds is the one it
/// was built to carry.
fn relink(entries: &mut [serde_json::Value], prev_hash: &str) {
    let mut previous = prev_hash.to_string();
    for entry in entries.iter_mut() {
        entry["prev_hash"] = serde_json::json!(previous);
        previous = value_entry_hash(entry);
        entry["entry_hash"] = serde_json::json!(previous);
    }
}

/// `entries` as a JSON Lines file.
fn json_lines(entries: &[serde_json::Value]) -> String {
    entries
        .iter()
        .map(|entry| entry.to_string() + "\n")
        .collect()
}

/// The `entry_hash` an entry held as raw JSON should carry: the digest of its
/// canonical form with `entry_hash` and `signature` removed (log spec 4).
fn value_entry_hash(entry: &serde_json::Value) -> String {
    let mut stripped = entry.clone();
    if let Some(object) = stripped.as_object_mut() {
        object.remove("entry_hash");
        object.remove("signature");
    }
    hushspec::canonical::digest(&hushspec::canonical::serialize_jcs(&stripped).unwrap())
}

fn expected_break_line(name: &str) -> usize {
    name.rsplit('-')
        .next()
        .and_then(|tail| tail.trim_end_matches(".jsonl").parse().ok())
        .unwrap_or_else(|| panic!("{name}: file name must end with the breaking line number"))
}

#[test]
fn log_vectors_are_current_and_behave() {
    let update = update_requested("HUSHSPEC_UPDATE_LOG_VECTORS");
    let generated = generate_vectors();
    if update {
        for (name, text) in &generated {
            let path = vectors_dir().join(name);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(&path, text).unwrap();
        }
    }
    let mut drift = Vec::new();
    for (name, text) in &generated {
        let path = vectors_dir().join(name);
        match fs::read_to_string(&path) {
            Ok(existing) if &existing == text => {}
            Ok(_) => drift.push(format!("{name} differs")),
            Err(_) => drift.push(format!("{name} is missing")),
        }
    }
    assert!(
        drift.is_empty(),
        "log vectors drifted (run with HUSHSPEC_UPDATE_LOG_VECTORS=1 after a deliberate change):\n{}",
        drift.join("\n")
    );

    // Behaviour of the committed files.
    let signed_options = LogVerifyOptions {
        require_signatures: false,
        keyring: Some(test_keyring()),
        verify: Some(verify_options()),
    };
    for name in ["valid/basic.jsonl", "valid/signed.jsonl"] {
        let text = fs::read_to_string(vectors_dir().join(name)).unwrap();
        verify_log(name, &text, &signed_options)
            .unwrap_or_else(|e| panic!("{name} must verify: {e}"));
    }
    let first = fs::read_to_string(vectors_dir().join("valid/rotated-1.jsonl")).unwrap();
    let second = fs::read_to_string(vectors_dir().join("valid/rotated-2.jsonl")).unwrap();
    verify_logs(
        &[("rotated-1", &first), ("rotated-2", &second)],
        &LogVerifyOptions::default(),
    )
    .expect("rotated pair verifies");

    let invalid_dir = vectors_dir().join("invalid");
    let mut count = 0;
    for entry in fs::read_dir(&invalid_dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let text = fs::read_to_string(&path).unwrap();
        let error = verify_log(&name, &text, &signed_options)
            .expect_err(&format!("{name} must be rejected"));
        assert_eq!(error.line, expected_break_line(&name), "{name}: {error}");
        count += 1;
    }
    assert!(
        count >= 8,
        "expected at least 8 invalid vectors, found {count}"
    );

    // The two payload vectors are hash-consistent throughout, so nothing but
    // the payload itself can reject them (log spec 8, step 1).
    for (name, missing) in [
        ("invalid/empty-log-started-line-1.jsonl", "timestamp"),
        ("invalid/policy-event-without-sdk-line-1.jsonl", "sdk"),
    ] {
        let text = fs::read_to_string(vectors_dir().join(name)).unwrap();
        let error = verify_log(name, &text, &signed_options).unwrap_err();
        assert!(
            error.message.contains(missing),
            "{name} must name the member it lacks: {error}"
        );
    }
}

/// Whether the caller asked for the committed vectors to be regenerated.
///
/// Only `1` and `true` count: `is_ok()` would make `VAR=0` regenerate, which
/// silently turns a verifying run into a rubber stamp.
fn update_requested(var: &str) -> bool {
    matches!(std::env::var(var).as_deref(), Ok("1") | Ok("true"))
}
