//! `fixtures/MANIFEST.json`: the conformance corpus inventory.
//!
//! The manifest pins the exact bytes of every vector an implementation was
//! tested against, so a conformance report can cite the corpus by digest
//! rather than by date. It is generated by
//! `scripts/generate_fixture_manifest.py`; this module reads it back, so the
//! runner and the report agree with the generator about what the corpus is.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Manifest format version this reader accepts. Fail-closed: an unknown
/// version is an error, not a best-effort parse.
pub const MANIFEST_VERSION: &str = "0.1";

/// Directories excluded from the manifest. `staged/` holds vectors for
/// behavior ratified in the spec but not yet shipped (core spec 1.1); they
/// are not part of any conformance level until promoted.
pub const EXCLUDED_PREFIXES: &[&str] = &["fixtures/staged/"];

/// The manifest file name, relative to the fixtures root.
pub const MANIFEST_FILE: &str = "MANIFEST.json";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Manifest {
    pub manifest_version: String,
    pub fixtures_version: String,
    pub generated_at: String,
    pub files: Vec<ManifestEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ManifestEntry {
    /// Repository-relative path with POSIX separators.
    pub path: String,
    /// Lowercase hex SHA-256 of the file's exact bytes.
    pub sha256: String,
    pub category: String,
    pub module: String,
    /// The conformance level (core spec 8) at which the vector is REQUIRED.
    pub level: u8,
}

#[derive(Debug, thiserror::Error)]
pub enum ManifestError {
    #[error("{path}: {message}")]
    Read { path: String, message: String },
    #[error("{path}: not a conformance manifest: {message}")]
    Parse { path: String, message: String },
    #[error("unsupported manifest_version {found:?} (this runner reads {MANIFEST_VERSION})")]
    UnsupportedVersion { found: String },
}

impl Manifest {
    /// Read and validate `<fixtures>/MANIFEST.json`.
    pub fn load(fixtures_dir: &Path) -> Result<Self, ManifestError> {
        let path = fixtures_dir.join(MANIFEST_FILE);
        let display = path.display().to_string();
        let text = std::fs::read_to_string(&path).map_err(|error| ManifestError::Read {
            path: display.clone(),
            message: error.to_string(),
        })?;
        let manifest: Manifest =
            serde_json::from_str(&text).map_err(|error| ManifestError::Parse {
                path: display,
                message: error.to_string(),
            })?;
        if manifest.manifest_version != MANIFEST_VERSION {
            return Err(ManifestError::UnsupportedVersion {
                found: manifest.manifest_version,
            });
        }
        Ok(manifest)
    }

    /// SHA-256 of the manifest file's bytes: what a report cites so the
    /// corpus it ran against is identified exactly.
    pub fn digest(fixtures_dir: &Path) -> Result<String, ManifestError> {
        let path = fixtures_dir.join(MANIFEST_FILE);
        let bytes = std::fs::read(&path).map_err(|error| ManifestError::Read {
            path: path.display().to_string(),
            message: error.to_string(),
        })?;
        Ok(digest_bytes(&bytes))
    }

    /// Manifest entries keyed by repository-relative path.
    #[must_use]
    pub fn by_path(&self) -> BTreeMap<&str, &ManifestEntry> {
        self.files
            .iter()
            .map(|entry| (entry.path.as_str(), entry))
            .collect()
    }

    /// The conformance level recorded for a fixture, looked up by a path that
    /// may be absolute: only the `fixtures/...` tail is compared, so a runner
    /// invoked from anywhere still matches.
    #[must_use]
    pub fn level_of(&self, path: &Path) -> Option<u8> {
        let needle = relative_fixture_path(path)?;
        self.files
            .iter()
            .find(|entry| entry.path == needle)
            .map(|entry| entry.level)
    }

    /// The manifest category recorded for a fixture.
    #[must_use]
    pub fn category_of(&self, path: &Path) -> Option<&str> {
        let needle = relative_fixture_path(path)?;
        self.files
            .iter()
            .find(|entry| entry.path == needle)
            .map(|entry| entry.category.as_str())
    }

    /// Compare the manifest with the tree it claims to describe.
    ///
    /// Returns one line per discrepancy: files present on disk but unlisted,
    /// listed but missing, and listed with a digest that no longer matches.
    /// An empty vector means the manifest is current.
    pub fn drift(&self, fixtures_dir: &Path) -> Result<Vec<String>, ManifestError> {
        let mut problems = Vec::new();
        let listed = self.by_path();

        let mut on_disk: Vec<String> = Vec::new();
        for path in walk(fixtures_dir) {
            let Some(relative) = relative_fixture_path(&path) else {
                continue;
            };
            if relative == format!("fixtures/{MANIFEST_FILE}")
                || EXCLUDED_PREFIXES
                    .iter()
                    .any(|prefix| relative.starts_with(prefix))
            {
                continue;
            }
            on_disk.push(relative.clone());
            match listed.get(relative.as_str()) {
                None => problems.push(format!("{relative} is not listed in the manifest")),
                Some(entry) => {
                    let bytes = std::fs::read(&path).map_err(|error| ManifestError::Read {
                        path: path.display().to_string(),
                        message: error.to_string(),
                    })?;
                    let actual = digest_bytes(&bytes);
                    if actual != entry.sha256 {
                        problems.push(format!(
                            "{relative}: manifest records {} but the file hashes to {actual}",
                            entry.sha256
                        ));
                    }
                }
            }
        }

        on_disk.sort();
        for entry in &self.files {
            if on_disk.binary_search(&entry.path).is_err() {
                problems.push(format!("{}: listed but not on disk", entry.path));
            }
        }

        problems.sort();
        Ok(problems)
    }
}

/// Lowercase hex SHA-256 of some bytes.
#[must_use]
pub fn digest_bytes(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

/// The `fixtures/...` tail of a path, with POSIX separators.
///
/// Fixture paths reach the runner in whatever form the caller passed
/// (`fixtures`, `./fixtures`, an absolute path), so everything that has to
/// line up with the manifest goes through this one normalization.
#[must_use]
pub fn relative_fixture_path(path: &Path) -> Option<String> {
    let text = path.to_string_lossy().replace('\\', "/");
    let index = text.rfind("fixtures/")?;
    Some(text[index..].to_string())
}

/// Every file under `dir`, recursively, sorted by path.
#[must_use]
pub fn walk(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(current) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.is_file() {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixtures_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures")
    }

    #[test]
    fn the_committed_manifest_matches_the_fixtures_tree() {
        let manifest = Manifest::load(&fixtures_dir()).expect("fixtures/MANIFEST.json loads");
        let drift = manifest.drift(&fixtures_dir()).expect("tree is readable");
        assert!(
            drift.is_empty(),
            "fixtures/MANIFEST.json is stale -- rerun scripts/generate_fixture_manifest.py:\n  {}",
            drift.join("\n  ")
        );
    }

    #[test]
    fn the_manifest_excludes_staged_vectors() {
        let manifest = Manifest::load(&fixtures_dir()).unwrap();
        assert!(
            !manifest
                .files
                .iter()
                .any(|entry| entry.path.starts_with("fixtures/staged/")),
            "staged vectors are not normative and must stay out of the manifest"
        );
    }

    #[test]
    fn every_entry_carries_a_level_and_a_category() {
        let manifest = Manifest::load(&fixtures_dir()).unwrap();
        assert!(!manifest.files.is_empty());
        for entry in &manifest.files {
            assert!(entry.level <= 5, "{}: level {}", entry.path, entry.level);
            assert!(!entry.category.is_empty(), "{}", entry.path);
            assert!(!entry.module.is_empty(), "{}", entry.path);
            assert_eq!(entry.sha256.len(), 64, "{}", entry.path);
        }
    }

    #[test]
    fn relative_paths_are_normalized_from_any_spelling() {
        assert_eq!(
            relative_fixture_path(Path::new("/tmp/x/fixtures/core/valid/a.yaml")).as_deref(),
            Some("fixtures/core/valid/a.yaml")
        );
        assert_eq!(
            relative_fixture_path(Path::new("fixtures/core/valid/a.yaml")).as_deref(),
            Some("fixtures/core/valid/a.yaml")
        );
        assert_eq!(relative_fixture_path(Path::new("elsewhere/a.yaml")), None);
    }
}
