export type { HushSpec, MergeStrategy, GovernanceMetadata, ControlMapping, Classification, LifecycleState } from './schema.js';
// Experimental, opt-in trusted invocation boundary. Legacy adapters are unchanged.
export { snapshotJson, hashJson, type SnapshotLimits } from './invocation/json.js';
export { InvocationRegistry, qualifiedToolTarget, type InvocationBinding, type InvocationArguments } from './invocation/registry.js';
export { AuthenticatedPolicy, typescriptInvocationEngine, type InvocationEngine,
  type PreparedInvocationEngine, type InvocationEngineIdentity } from './invocation/policy.js';
export { FileInvocationJournal, type InvocationJournal, type InvocationAcknowledgment,
  type InvocationEvent, type InvocationCheckpoint } from './invocation/journal.js';
export { verifyInvocationJournal, inspectInvocationJournal, type InvocationTrust,
  type InvocationVerification } from './invocation/verify.js';
export type {
  Rules,
  ForbiddenPathsRule,
  PathAllowlistRule,
  EgressRule,
  SecretPatternsRule,
  SecretPattern,
  PatchIntegrityRule,
  ShellCommandsRule,
  ToolAccessRule,
  ComputerUseRule,
  ComputerUseMode,
  RemoteDesktopChannelsRule,
  InputInjectionRule,
  BrowserAutomationRule,
  CodeExecutionRule,
  Severity,
  DefaultAction,
} from './rules.js';
export type {
  Extensions,
  PostureExtension,
  PostureState,
  PostureTransition,
  TransitionTrigger,
  OriginsExtension,
  OriginDefaultBehavior,
  OriginProfile,
  OriginToolAccessOverlay,
  OriginEgressOverlay,
  OriginMatch,
  OriginDataPolicy,
  OriginBudgets,
  BridgePolicy,
  BridgeTarget,
  DetectionExtension,
  PromptInjectionDetection,
  PromptInjectionHeuristics,
  DetectionLevel,
  JailbreakDetection,
  ThreatIntelDetection,
} from './extensions.js';
export {
  parse,
  parseOrThrow,
  yamlProfileViolation,
  MAX_DOCUMENT_BYTES,
  MAX_DOCUMENT_DEPTH,
  MAX_NODE_COUNT,
  type ParseResult,
} from './parse.js';
export {
  validate,
  isSafeRegex,
  type ValidationResult,
  type ValidationError,
  type ErrorCode,
} from './validate.js';
export { merge } from './merge.js';
export {
  canonicalJson,
  canonicalizeValue,
  contentHash,
  CanonicalError,
  type JsonValue,
} from './canonical.js';
export {
  signPolicy,
  verifyPolicy,
  parseEnvelope,
  envelopeSigningInput,
  loadKeyring,
  keyringFromPublicKey,
  keyIdFromPublicKey,
  publicKeyPemFromPrivateKey,
  generateKeypair,
  signContentHash,
  verifyContentHash,
  signReceipt,
  verifyReceipt,
  Keyring,
  SigningError,
  SIGNATURE_FORMAT_VERSION,
  SIGNATURE_ALGORITHM,
  KEYRING_VERSION,
  DEFAULT_MAX_CLOCK_SKEW_SECONDS,
  type Envelope,
  type ReasonCode,
  type SignOptions,
  type VerifyOptions,
  type VerificationOutcome,
  type VerificationSuccess,
  type VerificationFailure,
  type TrustedKey,
  type TrustedKeyDocument,
  type KeyringDocument,
  type GeneratedKeypair,
  type SignedReceipt,
} from './signing.js';
export {
  resolve,
  resolveFromFile,
  resolveWithOptions,
  resolveWithOptionsAsync,
  resolveFromFileWithOptions,
  createCompositeLoader,
  createBuiltinLoader,
  defaultSignatureLocator,
  defaultAsyncSignatureLocator,
  splitDigestPin,
  resolutionFromResolved,
  resolveErrorReason,
  isLoadReasonCode,
  loadReasonOf,
  PolicyVerificationError,
  ResolveError,
  MEMORY_SOURCE,
  INLINE_POLICY_SOURCE,
  type LoadedSpec,
  type Loader,
  type AsyncLoader,
  type ResolveInput,
  type AsyncResolveInput,
  type ResolveOptions,
  type ResolveResult,
  type Resolution,
  type ChainLink,
  type SignatureStatus,
  type SignatureLocator,
  type VerifyClockOptions,
  type LoadReasonCode,
  type ResolveReasonCode,
} from './resolve.js';
export {
  verifyBundle,
  createBundle,
  buildBundleStatement,
  bundleStatementBytes,
  bundleToJson,
  parseBundle,
  bundleStatement,
  pae,
  BundleError,
  BUNDLE_REASONS,
  BUNDLE_VERSION,
  BUNDLE_PAYLOAD_TYPE,
  BUNDLE_STATEMENT_TYPE,
  BUNDLE_PREDICATE_TYPE,
  BUNDLE_RESOLVER_TOOL,
  type CreateBundleOptions,
  type DsseEnvelope,
  type DsseSignature,
  type BundleStatement,
  type BundleSubject,
  type SubjectDigest,
  type BundleResolver,
  type BundlePolicyIdentity,
  type PolicyBundlePredicate,
  type BundleReason,
  type BundleVerified,
  type BundleVerificationFailure,
  type BundleVerificationOutcome,
  type VerifyBundleOptions,
} from './bundle.js';
export { loadBuiltin, BUILTIN_NAMES, type BuiltinName } from './builtin.js';
export {
  createHttpLoader,
  createSyncHttpLoader,
  fetchSignature,
  httpSignatureLocator,
  isBlockedAddress,
  resolveTarget,
  CLOUD_METADATA_ADDRESSES,
  DEFAULT_CONNECT_TIMEOUT_MS,
  DEFAULT_READ_TIMEOUT_MS,
  DEFAULT_MAX_SIZE,
  type HttpLoaderConfig,
  type HttpTarget,
} from './http-loader.js';
export {
  compilePolicy,
  compileResolution,
  CompiledPolicy,
  CompileError,
  type CompileOptions,
} from './compiled.js';
export {
  evaluate,
  evaluateTraced,
  evaluateWithContext,
  activatePanic,
  deactivatePanic,
  isPanicActive,
  panicPolicy,
  checkPanicSentinel,
  DEFAULT_PANIC_SENTINEL,
  normalizeHost,
  normalizePath,
  hostPatternMatches,
  pathGlobMatches,
  punycodeEncode,
  UNKNOWN_ACTION_TYPE_RULE,
  PANIC_RULE,
  BUILTIN_CREDENTIAL_PATTERNS,
  type EvaluationAction,
  type EvaluationResult,
  type TracedEvaluation,
  type Decision,
  type OriginContext,
  type PostureContext,
  type PostureResult,
} from './evaluate.js';
export {
  evaluateCondition,
  evaluateConditionWithCapabilities,
  isCapabilityIdentifier,
  validateCondition,
  validateConditions,
  timezoneIsKnown,
  MAX_NESTING_DEPTH,
  DAY_ABBREVIATIONS,
  RATE_COMPARISONS,
  CONDITION_RULE_BLOCKS,
  type Condition,
  type TimeWindowCondition,
  type RateCondition,
  type RateComparison,
  type GrantedCapabilities,
  type RuntimeContext,
} from './conditions.js';
export {
  HushGuard,
  HushSpecDenied,
  matchesRulePathPrefix,
  resolvePolicyOrThrow,
  resolvePolicyResolution,
  POLICY_SIGNATURE_RULE,
  type WarnHandler,
  type EnforcementConfig,
  type GateOutcome,
  type HushGuardOptions,
  type PolicyResolveOptions,
} from './middleware.js';
export { mapClaudeToolToAction, createSecureToolHandler } from './adapters/anthropic.js';
export { mapOpenAIToolCall, createOpenAIGuard } from './adapters/openai.js';
export { mapMCPToolCall, extractDomain, createMCPGuard } from './adapters/mcp.js';
export {
  mapVercelToolCall,
  createVercelGuard,
  type VercelToolCall,
  type VercelTool,
  type VercelGuard,
} from './adapters/vercel.js';
export {
  mapLangChainToolCall,
  wrapLangChainTool,
  createLangChainCallbackHandler,
  createLangChainGuard,
  type LangChainToolLike,
  type LangChainSerializedTool,
  type LangChainCallbackHandler,
} from './adapters/langchain.js';
export {
  HUSHSPEC_VERSION,
  SDK_NAME,
  SDK_VERSION,
  HUSHSPEC_SUPPORTED_MINORS,
  HUSHSPEC_SUPPORTED_VERSIONS,
  SUPPORTED_VERSIONS,
  isSupported,
  supportedMinor,
} from './version.js';
export {
  evaluateAudited,
  evaluateAuditedSpec,
  unverifiedPolicyReceipt,
  policySummary,
  computePolicyHash,
  canonicalJson as receiptCanonicalJson,
  receiptHash,
  parseReceipt,
  formatTimestamp,
  deterministicUuidV7,
  uuidV7,
  impliedEnforcement,
  compactObject,
  actorIsEmpty,
  ReceiptError,
  DEFAULT_AUDIT_CONFIG,
  RECEIPT_VERSION,
  ORIGIN_PROFILE_BLOCK,
  UNKNOWN_ACTION_TYPE_BLOCK,
  POLICY_UNVERIFIED_RULE,
  type DecisionReceipt,
  type ActionSummary,
  type Actor,
  type ReceiptChainLink,
  type RuleEvaluation,
  type RuleOutcome,
  type RuleTraceEntry,
  type TimeSource,
  type EnforcementMode,
  type EnforcementOutcome,
  type EnforcementSummary,
  type PolicySummary,
  type AuditConfig,
  type AuditContext,
} from './receipt.js';
export {
  ChainedFileSink,
  verifyLog,
  verifyLogs,
  verifyLogFiles,
  computeEntryHash,
  payloadMatchesType,
  policyLoadedEvent,
  policySwappedEvent,
  thisSdk,
  LogChainError,
  LOG_VERSION,
  GENESIS_HASH,
  REASON_UNSIGNED,
  LOCK_TIMEOUT_MS,
  type LogEntry,
  type EntryType,
  type PolicyEvent,
  type PolicyEventKind,
  type SdkInfo,
  type LogStarted,
  type LogSignature,
  type Payload,
  type LogVerifyOptions,
  type LogVerifyReport,
  type LogBreak,
} from './log.js';
export {
  type ReceiptSink,
  FileReceiptSink,
  ConsoleReceiptSink,
  StderrReceiptSink,
  FilteredSink,
  MultiSink,
  CallbackSink,
  NullSink,
} from './sinks.js';
export {
  OtlpReceiptSink,
  OtlpQueueOverflowError,
  OtlpExportError,
  otlpLogsPayload,
  receiptLogRecord,
  policyEventLogRecord,
  logsEndpoint,
  RETRYABLE_STATUSES,
  type OtlpReceiptSinkOptions,
  type OtlpLogsPayload,
  type OtlpLogRecord,
  type OtlpAttribute,
  type OtlpStringValue,
  type OtlpEntry,
} from './otlp.js';
export {
  evaluateWithDetection,
  evaluateWithDetectionTraced,
  detectorLevel,
  DetectorRegistry,
  RegexInjectionDetector,
  RegexJailbreakDetector,
  RegexExfiltrationDetector,
  HeuristicInjectionDetector,
  HEURISTIC_DETECTOR_NAME,
  HEURISTIC_FAMILIES,
  HEURISTIC_UPPERCASE_WEIGHT,
  HEURISTIC_UPPERCASE_MIN_LETTERS,
  HEURISTIC_UPPERCASE_MIN_PERCENT,
  type DetectionCategory,
  type DetectionResult,
  type MatchedPattern,
  type Detector,
  type EvaluationWithDetection,
  type TracedEvaluationWithDetection,
  type DetectorEvaluation,
  type DetectorLevel,
} from './detection.js';
export { PolicyWatcher, type WatcherOptions } from './watcher.js';
export {
  PolicyPoller,
  DEFAULT_POLL_INTERVAL_MS,
  type PollerOptions,
  type PolicySnapshot,
} from './poller.js';
export {
  type PolicyProvider,
  type ProviderResolveOptions,
  FileProvider,
  HttpProvider,
  DEFAULT_SENTINEL_INTERVAL_MS,
} from './policy-provider.js';
export {
  ObservableEvaluator,
  JsonLineObserver,
  ConsoleObserver,
  MetricsCollector,
  DURATION_BUCKETS_US,
  DURATION_WINDOW,
  ruleBlockOf,
  type EvaluationObserver,
  type EvaluationEvent,
  type EvaluationCompletedEvent,
  type PolicyLoadedEvent,
  type PolicyLoadFailedEvent,
  type PolicyReloadedEvent,
  type SinkErrorEvent,
  type ObserverErrorEvent,
  type ObserverEvent,
} from './observer.js';
