#!/usr/bin/env python3
"""Generate the core crate's embedded schemas for the canonical projection.

The canonical projection (spec/hushspec-canonical.md section 3) is defined by
walking a resolved document alongside the published JSON Schemas, so
`hushspec::canonical` needs the schema bodies at runtime. `cargo package`
cannot reach files outside the crate directory, so the core crate cannot
`include_str!("../../../schemas/...")`; the bodies are embedded in a
committed, generated source file the way the CLI embeds its own copies
(scripts/generate_cli_schemas.py).

Only the four schemas the projection walks are embedded: the core schema and
the three extension schemas. `h2h schema` still serves every schema from the
CLI's own generated module.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = ROOT / "schemas"
OUTPUT = ROOT / "crates" / "hushspec" / "src" / "generated_canonical_schemas.rs"

CORE_SCHEMA = "hushspec-core.v1.schema.json"
# `extensions` key -> schema file, in the order the constant is rendered.
EXTENSION_SCHEMAS = {
    "detection": "hushspec-detection.v1.schema.json",
    "origins": "hushspec-origins.v1.schema.json",
    "posture": "hushspec-posture.v1.schema.json",
}


def read_schema(file_name: str) -> str:
    path = SCHEMAS_DIR / file_name
    if not path.is_file():
        raise SystemExit(f"missing schema {path}")
    body = path.read_text(encoding="utf-8")
    # Validate as JSON here so a malformed schema fails the generator rather
    # than every canonicalization at runtime.
    json.loads(body)
    return body


def raw_string(body: str) -> str:
    """Render `body` as a Rust raw string literal with enough hashes.

    Schema bodies contain `"#/$defs/..."` refs, so `r#"..."#` would terminate
    early; pick the smallest hash count that cannot appear.
    """
    hashes = 1
    while f'"{"#" * hashes}' in body:
        hashes += 1
    pad = "#" * hashes
    return f'r{pad}"{body}"{pad}'


def render() -> str:
    lines = [
        "// Code generated by scripts/generate_canonical_schemas.py. DO NOT EDIT.",
        "//",
        "// Source: schemas/*.json at the workspace root. Regenerate with:",
        "//   python3 scripts/generate_canonical_schemas.py",
        "//",
        "// The canonical projection (spec/hushspec-canonical.md section 3) walks",
        "// these schemas. They are embedded rather than `include_str!`d because",
        "// `cargo package` cannot reach files outside the crate directory.",
        "",
        "/// File name of the core schema, as published under `schemas/`.",
        f"pub(crate) const CORE_SCHEMA_NAME: &str = {json.dumps(CORE_SCHEMA)};",
        "",
        "/// Body of the core schema.",
        f"pub(crate) const CORE_SCHEMA: &str = {raw_string(read_schema(CORE_SCHEMA))};",
        "",
    ]

    for key, file_name in EXTENSION_SCHEMAS.items():
        upper = key.upper()
        lines.extend(
            [
                f"/// File name of the {key} extension schema.",
                f"pub(crate) const {upper}_SCHEMA_NAME: &str = {json.dumps(file_name)};",
                "",
                f"/// Body of the {key} extension schema.",
                f"pub(crate) const {upper}_SCHEMA: &str = {raw_string(read_schema(file_name))};",
                "",
            ]
        )

    lines.extend(
        [
            "/// The extension schemas the projection walks, as",
            "/// `(extensions key, schema file name, schema body)`.",
            "pub(crate) const EXTENSION_SCHEMAS: &[(&str, &str, &str)] = &[",
        ]
    )
    for key in EXTENSION_SCHEMAS:
        upper = key.upper()
        lines.append(f"    ({json.dumps(key)}, {upper}_SCHEMA_NAME, {upper}_SCHEMA),")
    lines.extend(["];", ""])

    content = "\n".join(lines)

    # Run the output through rustfmt, exactly as generate_cli_schemas.py does.
    # Without this, `cargo fmt --all` reformats the committed file and
    # `--check` then reports it as permanently stale.
    rustfmt = shutil.which("rustfmt")
    if rustfmt is None:
        return content

    result = subprocess.run(
        [rustfmt, "--emit", "stdout", "--edition", "2021"],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed file differs from the generated output",
    )
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != content:
            print(
                f"{OUTPUT.relative_to(ROOT)} is stale; "
                "run python3 scripts/generate_canonical_schemas.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
