#!/usr/bin/env python3
"""Generate the Go built-in ruleset file from canonical YAML files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RULESETS_DIR = ROOT / "rulesets"
OUTPUT = ROOT / "packages" / "go" / "hushspec" / "builtins.go"

BUILTIN_NAMES = [
    "default",
    "strict",
    "permissive",
    "ai-agent",
    "cicd",
    "remote-desktop",
]


def render() -> str:
    # json.dumps produces a double-quoted, escaped string whose escape set
    # (\n \t \r \" \\ \uXXXX ...) is a subset of Go's interpreted string
    # literal escapes, so it is a valid Go string literal.
    lines = [
        "// Code generated by scripts/generate_go_builtins.py. DO NOT EDIT.",
        "",
        "package hushspec",
        "",
        'import "strings"',
        "",
        "var builtinRulesets = map[string]string{",
    ]

    # gofmt aligns the values of consecutive single-line map entries: each key
    # is padded with spaces so every value starts one column past the widest
    # `"key":`. Replicate that here so the output is gofmt-clean without needing
    # gofmt on PATH (the Generated Sources CI job has only Python).
    key_col = {name: len(json.dumps(name)) + 1 for name in BUILTIN_NAMES}  # +1 for ':'
    value_col = max(key_col.values()) + 1

    for name in BUILTIN_NAMES:
        yaml_content = (RULESETS_DIR / f"{name}.yaml").read_text()
        pad = " " * (value_col - key_col[name])
        lines.append(f"\t{json.dumps(name)}:{pad}{json.dumps(yaml_content)},")

    lines.extend(
        [
            "}",
            "",
            "// LoadBuiltin parses the built-in ruleset for name (with or without the",
            '// "builtin:" prefix) and reports whether the name was found.',
            "func LoadBuiltin(name string) (*HushSpec, bool) {",
            '\tresolved := strings.TrimPrefix(name, "builtin:")',
            "\tyaml, ok := builtinRulesets[resolved]",
            "\tif !ok {",
            "\t\treturn nil, false",
            "\t}",
            "\tspec, err := Parse(yaml)",
            "\tif err != nil {",
            "\t\treturn nil, false",
            "\t}",
            "\treturn spec, true",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if builtins.go is out of date"
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
