#!/usr/bin/env python3
"""Generate the Python built-in ruleset module from canonical YAML files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RULESETS_DIR = ROOT / "rulesets"
OUTPUT = ROOT / "packages" / "python" / "hushspec" / "builtins.py"

BUILTIN_NAMES = [
    "default",
    "strict",
    "permissive",
    "ai-agent",
    "cicd",
    "remote-desktop",
]


def render() -> str:
    lines = [
        "# Code generated by scripts/generate_python_builtins.py. DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "from hushspec.parse import parse",
        "from hushspec.schema import HushSpec",
        "",
        "BUILTIN_NAMES = (",
    ]

    for name in BUILTIN_NAMES:
        lines.append(f"    {json.dumps(name)},")

    lines.extend(
        [
            ")",
            "",
            "_BUILTIN_RULESETS: dict[str, str] = {",
        ]
    )

    for name in BUILTIN_NAMES:
        yaml_content = (RULESETS_DIR / f"{name}.yaml").read_text()
        lines.append(f"    {json.dumps(name)}: {json.dumps(yaml_content)},")

    lines.extend(
        [
            "}",
            "",
            "",
            "def load_builtin(name: str) -> HushSpec | None:",
            '    """Parse the built-in ruleset for ``name`` (with or without the',
            '    ``builtin:`` prefix), or return ``None`` if the name is unknown."""',
            "    resolved = name[len('builtin:'):] if name.startswith('builtin:') else name",
            "    yaml = _BUILTIN_RULESETS.get(resolved)",
            "    if yaml is None:",
            "        return None",
            "    ok, parsed = parse(yaml)",
            "    if not ok:",
            "        return None",
            "    return parsed",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if builtins.py is out of date"
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
