#!/usr/bin/env python3
"""Generate the h2h CLI's embedded framework registry from spec/registries/.

Lint L013 checks `metadata.controls[].framework` against the registry in
spec/registries/frameworks.yaml, but `cargo package` cannot reach files outside
the crate directory, so the CLI cannot `include_str!` the registry the way the
core crate embeds rulesets. Committing the registry as a generated Rust source
keeps L013 working from a published crate with no publish-time patching, and
mirrors scripts/generate_cli_schemas.py.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "spec" / "registries" / "frameworks.yaml"
OUTPUT = ROOT / "crates" / "hushspec-cli" / "src" / "generated_frameworks.rs"

FRAMEWORK_ID_RE = re.compile(r"^[a-z0-9][a-z0-9.-]*$")
FIELDS = ("id", "name", "version", "url", "control_id_pattern")


def load() -> tuple[str, list[dict]]:
    """Return (registry_version, frameworks) after validating the source file."""
    data = yaml.safe_load(REGISTRY.read_text())

    if not isinstance(data, dict):
        raise SystemExit(f"{REGISTRY} must be a YAML mapping")

    unknown = set(data) - {"registry_version", "frameworks"}
    if unknown:
        raise SystemExit(f"{REGISTRY} has unknown top-level keys: {sorted(unknown)}")

    version = data.get("registry_version")
    if not isinstance(version, str):
        raise SystemExit(f"{REGISTRY} is missing a string registry_version")

    frameworks = data.get("frameworks")
    if not isinstance(frameworks, list) or not frameworks:
        raise SystemExit(f"{REGISTRY} must list at least one framework")

    seen: set[str] = set()
    for entry in frameworks:
        if not isinstance(entry, dict):
            raise SystemExit(f"{REGISTRY}: every framework must be a mapping")
        missing = [key for key in FIELDS if not isinstance(entry.get(key), str) or not entry[key]]
        if missing:
            raise SystemExit(f"{REGISTRY}: framework {entry.get('id')!r} is missing {missing}")
        unknown = set(entry) - set(FIELDS)
        if unknown:
            raise SystemExit(f"{REGISTRY}: framework {entry['id']!r} has unknown keys {sorted(unknown)}")
        if FRAMEWORK_ID_RE.match(entry["id"]) is None:
            raise SystemExit(f"{REGISTRY}: framework id {entry['id']!r} must match ^[a-z0-9][a-z0-9.-]*$")
        pattern = entry["control_id_pattern"]
        if not (pattern.startswith("^") and pattern.endswith("$")):
            raise SystemExit(f"{REGISTRY}: {entry['id']}: control_id_pattern must be anchored")
        try:
            re.compile(pattern)
        except re.error as exc:
            raise SystemExit(f"{REGISTRY}: {entry['id']}: control_id_pattern does not compile: {exc}")
        if entry["id"] in seen:
            raise SystemExit(f"{REGISTRY}: duplicate framework id {entry['id']!r}")
        seen.add(entry["id"])

    ids = [entry["id"] for entry in frameworks]
    if ids != sorted(ids):
        raise SystemExit(f"{REGISTRY}: frameworks must be sorted by id")

    return version, frameworks


def render() -> str:
    version, frameworks = load()

    lines = [
        "// Code generated by scripts/generate_cli_frameworks.py. DO NOT EDIT.",
        "//",
        "// Source: spec/registries/frameworks.yaml. Regenerate with:",
        "//   python3 scripts/generate_cli_frameworks.py",
        "",
        "/// One registered compliance framework (spec/registries/frameworks.yaml).",
        "#[derive(Clone, Copy, Debug, serde::Serialize)]",
        "pub struct Framework {",
        "    /// Registry id, as named by `metadata.controls[].framework`.",
        "    pub id: &'static str,",
        "    /// Human-readable framework name.",
        "    pub name: &'static str,",
        "    /// Edition, revision, or publication year the control ids refer to.",
        "    pub version: &'static str,",
        "    /// Canonical location of the framework text.",
        "    pub url: &'static str,",
        "    /// Anchored regex every `control_id` for this framework must match.",
        "    pub control_id_pattern: &'static str,",
        "}",
        "",
        "/// Version of the registry file this table was generated from.",
        f"pub const REGISTRY_VERSION: &str = {json.dumps(version)};",
        "",
        "/// Registered frameworks, sorted by id.",
        "pub const FRAMEWORKS: &[Framework] = &[",
    ]

    for entry in frameworks:
        lines.append("    Framework {")
        for key in FIELDS:
            lines.append(f"        {key}: {json.dumps(entry[key])},")
        lines.append("    },")

    lines.extend(
        [
            "];",
            "",
            "/// Look up a registered framework by id.",
            "#[must_use]",
            "pub fn framework(id: &str) -> Option<&'static Framework> {",
            "    FRAMEWORKS.iter().find(|entry| entry.id == id)",
            "}",
            "",
        ]
    )

    content = "\n".join(lines)

    # Run the output through rustfmt so `cargo fmt --all` and this generator
    # agree: otherwise a long framework name or URL wraps under cargo fmt and
    # `--check` reports the committed file as permanently stale.
    rustfmt = shutil.which("rustfmt")
    if rustfmt is None:
        return content

    result = subprocess.run(
        [rustfmt, "--emit", "stdout", "--edition", "2021"],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated_frameworks.rs is out of date",
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
