#!/usr/bin/env python3
"""Generate the Python built-in ruleset module from canonical YAML files."""

from __future__ import annotations

import argparse
import json
import sys

from generator_support import ROOT, PANIC_NAME, all_builtin_names, builtin_yaml


OUTPUT = ROOT / "packages" / "python" / "hushspec" / "builtins.py"


def render() -> str:
    lines = [
        "# Code generated by scripts/generate_python_builtins.py. DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "from hushspec.parse import parse",
        "from hushspec.schema import HushSpec",
        "",
        "BUILTIN_NAMES = (",
    ]

    names = all_builtin_names()

    for name in names:
        lines.append(f"    {json.dumps(name)},")

    lines.extend(
        [
            ")",
            "",
            "_BUILTIN_RULESETS: dict[str, str] = {",
        ]
    )

    for name in names:
        lines.append(
            f"    {json.dumps(name)}: {json.dumps(builtin_yaml(name), ensure_ascii=False)},"
        )

    lines.extend(
        [
            "}",
            "",
            "#: The emergency deny-all policy the panic protocol enforces (core spec 6.2),",
            "#: from rulesets/panic.yaml. Not a built-in name: ``extends: builtin:panic``",
            "#: does not resolve.",
            f"PANIC_POLICY_YAML = {json.dumps(builtin_yaml(PANIC_NAME), ensure_ascii=False)}",
            "",
            "",
            "def load_builtin(name: str) -> HushSpec | None:",
            '    """Parse the built-in ruleset for ``name`` (with or without the',
            '    ``builtin:`` prefix), or return ``None`` if the name is unknown.',
            "",
            "    A ruleset that is present but does not parse raises: an embedded document",
            "    is generated from ``rulesets/``, so a failure there is a broken build, and",
            '    reporting it as ``None`` would surface downstream as "unknown builtin".',
            '    """',
            "    resolved = name[len('builtin:'):] if name.startswith('builtin:') else name",
            "    yaml = _BUILTIN_RULESETS.get(resolved)",
            "    if yaml is None:",
            "        return None",
            "    ok, parsed = parse(yaml)",
            "    if not ok:",
            "        raise ValueError(f'built-in ruleset {resolved!r} does not parse: {parsed}')",
            "    return parsed",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if builtins.py is out of date"
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
