#!/usr/bin/env python3
"""Generate the TypeScript built-in ruleset module from canonical YAML files."""

from __future__ import annotations

import argparse
import json
import sys

from generator_support import ROOT, PANIC_NAME, all_builtin_names, builtin_yaml


OUTPUT = ROOT / "packages" / "hushspec" / "src" / "builtin.ts"


def render() -> str:
    lines = [
        "// Code generated by scripts/generate_ts_builtins.py. DO NOT EDIT.",
        "",
        "import type { HushSpec } from './schema.js';",
        "import { parseOrThrow } from './parse.js';",
        "",
        "export const BUILTIN_NAMES = [",
    ]

    names = all_builtin_names()

    for name in names:
        lines.append(f"  {json.dumps(name)},")

    lines.extend(
        [
            "] as const;",
            "",
            "export type BuiltinName = (typeof BUILTIN_NAMES)[number];",
            "",
            "const BUILTIN_RULESETS: Record<BuiltinName, string> = {",
        ]
    )

    for name in names:
        lines.append(
            f"  {json.dumps(name)}: {json.dumps(builtin_yaml(name), ensure_ascii=False)},"
        )

    lines.extend(
        [
            "};",
            "",
            "/**",
            " * The emergency deny-all policy the panic protocol enforces (core spec 6.2),",
            " * from rulesets/panic.yaml. Not a built-in name: `extends: builtin:panic`",
            " * does not resolve.",
            " */",
            f"export const PANIC_POLICY_YAML = {json.dumps(builtin_yaml(PANIC_NAME), ensure_ascii=False)};",
            "",
            "/**",
            " * The built-in ruleset for `name` (with or without the `builtin:` prefix),",
            " * or `null` for a name that is not built in.",
            " *",
            " * An embedded ruleset that does not parse throws: it is generated from",
            " * rulesets/, so a failure there is a broken build, not an unknown built-in.",
            " */",
            "export function loadBuiltin(name: string): HushSpec | null {",
            "  const resolved = name.startsWith('builtin:') ? name.slice(8) : name;",
            "",
            "  if (!(BUILTIN_NAMES as readonly string[]).includes(resolved)) {",
            "    return null;",
            "  }",
            "",
            "  const yaml = BUILTIN_RULESETS[resolved as BuiltinName];",
            "  try {",
            "    return parseOrThrow(yaml);",
            "  } catch (error) {",
            "    const message = error instanceof Error ? error.message : String(error);",
            "    throw new Error(`built-in ruleset '${resolved}' does not parse: ${message}`);",
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if builtin.ts is out of date")
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
