#!/usr/bin/env python3
"""Generate the Rust built-in ruleset module from canonical YAML files."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RULESETS_DIR = ROOT / "rulesets"
OUTPUT = ROOT / "crates" / "hushspec" / "src" / "generated_builtins.rs"

BUILTIN_NAMES = [
    "default",
    "strict",
    "permissive",
    "ai-agent",
    "cicd",
    "remote-desktop",
]


LIBRARY_DIR = ROOT / "library"


def library_names() -> list[str]:
    """Every vertical-library policy, as `library/<vertical>/<name>`.

    The library ships as built-ins alongside `rulesets/` so that
    `extends: "builtin:library/healthcare/hipaa-base"` resolves with no file
    system, in every SDK. Discovered rather than listed, so adding a policy to
    `library/` is one commit; the `library/` prefix keeps the existing
    `rulesets/` names unchanged.
    """
    return sorted(
        f"library/{path.parent.name}/{path.stem}"
        for path in LIBRARY_DIR.glob("*/*.yaml")
    )


def all_builtin_names() -> list[str]:
    """`rulesets/` first (historical order), then the library."""
    return BUILTIN_NAMES + library_names()


def builtin_yaml(name: str) -> str:
    """The canonical YAML for a built-in name."""
    if name.startswith("library/"):
        return (ROOT / f"{name}.yaml").read_text()
    return (RULESETS_DIR / f"{name}.yaml").read_text()


# Embedded alongside the built-ins but deliberately *not* in BUILTIN_NAMES:
# `extends: builtin:panic` is not a thing, the panic policy is only reachable
# through the emergency kill switch.
PANIC_NAME = "panic"


def rust_string_literal(value: str) -> str:
    """Render `value` as a Rust double-quoted string literal.

    Written by hand rather than reusing `json.dumps` (as the TS/Python/Go
    generators do) because JSON and Rust disagree on two escapes: JSON emits
    control characters as `\\uXXXX`, which Rust rejects (it spells them
    `\\u{XX}`), and JSON has no `\\0`. Non-ASCII is emitted raw as UTF-8,
    which a Rust string literal accepts verbatim.
    """
    out = ['"']
    for char in value:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif ord(char) < 0x20 or ord(char) == 0x7F:
            out.append(f"\\u{{{ord(char):x}}}")
        else:
            out.append(char)
    out.append('"')
    return "".join(out)


def const_ident(name: str) -> str:
    return name.upper().replace("-", "_").replace("/", "_") + "_YAML"


def render() -> str:
    lines = [
        "// Code generated by scripts/generate_rust_builtins.py. DO NOT EDIT.",
        "//",
        "// The canonical sources are rulesets/*.yaml and library/*/*.yaml (embedded",
        "// under their `library/<vertical>/<name>` builtin names). The YAML is embedded",
        "// as string literals rather than `include_str!` because both directories live",
        "// outside the crate directory: an `include_str!(\"../../../rulesets/...\")` does",
        "// not survive `cargo package`, which copies only files under crates/hushspec/.",
        "",
    ]

    # One long line per ruleset: rustfmt cannot break a string literal, so it
    # collapses a wrapped `const X: &str =\n    "...";` back onto one line.
    # Emitting that form directly keeps `--check` stable under `cargo fmt`.
    names = all_builtin_names()

    for name in names + [PANIC_NAME]:
        literal = rust_string_literal(builtin_yaml(name))
        lines.append(f"pub(crate) const {const_ident(name)}: &str = {literal};")

    lines.extend(
        [
            "",
            "/// Canonical names of the built-in rulesets.",
            "pub(crate) const BUILTIN_NAMES: &[&str] = &[",
        ]
    )

    for name in names:
        lines.append(f"    {rust_string_literal(name)},")

    lines.extend(
        [
            "];",
            "",
            "/// Built-in ruleset YAML keyed by name, in `BUILTIN_NAMES` order.",
            "pub(crate) const BUILTIN_RULESETS: &[(&str, &str)] = &[",
        ]
    )

    for name in names:
        lines.append(f"    ({rust_string_literal(name)}, {const_ident(name)}),")

    lines.extend(["];", ""])
    content = "\n".join(lines)

    # Run the output through rustfmt, exactly as generate_cli_schemas.py does.
    # A `("library/<vertical>/<name>", IDENT)` entry sits right at the width
    # where rustfmt starts breaking a tuple across lines; asking rustfmt rather
    # than reimplementing its heuristic keeps `cargo fmt --check` and this
    # generator's `--check` from disagreeing about the committed bytes.
    rustfmt = shutil.which("rustfmt")
    if rustfmt is None:
        raise SystemExit(
            "rustfmt is not on PATH, and generated_builtins.rs is committed as rustfmt "
            "output. Generating without it would write a file that `cargo fmt` "
            "immediately reformats, which this script's --check then reports "
            "as out of date forever. Install it with `rustup component add "
            "rustfmt`."
        )

    result = subprocess.run(
        [rustfmt, "--emit", "stdout", "--edition", "2024"],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated_builtins.rs is out of date",
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
