#!/usr/bin/env python3
"""Generate the h2h CLI's embedded JSON Schema module from schemas/.

`cargo package` cannot reach files outside the crate directory, so the CLI
cannot `include_str!("../../schemas/...")` the way the core crate embeds
rulesets (publish.yml sed-patches those paths at publish time). Embedding the
schema bodies in a committed, generated source file keeps `h2h schema` working
from a published crate with no publish-time patching.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = ROOT / "schemas"
OUTPUT = ROOT / "crates" / "hushspec-cli" / "src" / "generated_schemas.rs"

FILENAME_RE = re.compile(r"^hushspec-(?P<name>[a-z0-9-]+)\.v(?P<lineage>\d+)\.schema\.json$")

# Files in schemas/ that are not schemas themselves.
NON_SCHEMA_FILES = {"frozen-v0.json"}


def discover() -> list[tuple[str, str, str]]:
    """Return (short_name, file_name, body) triples in the order `h2h schema --list` prints.

    The current lineage (`.v1.`) takes the bare short name; the frozen `.v0.`
    lineage keeps a `.v0` suffix; registries exist only at `.v0` and keep their
    bare name. Current document formats come first, then registries, then the
    frozen lineage.
    """
    entries: list[tuple[str, str, str, int]] = []

    for path in sorted(SCHEMAS_DIR.glob("*.json")):
        if path.name in NON_SCHEMA_FILES:
            continue
        match = FILENAME_RE.match(path.name)
        if not match:
            raise SystemExit(
                f"{path.name} does not match hushspec-<name>.v<lineage>.schema.json; "
                "update scripts/generate_cli_schemas.py if the naming changed"
            )
        body = path.read_text()
        # Validate as JSON so a malformed schema fails the generator, not the
        # user running `h2h schema`.
        json.loads(body)
        entries.append((match.group("name"), path.name, body, int(match.group("lineage"))))

    if not entries:
        raise SystemExit(f"no schemas found in {SCHEMAS_DIR}")

    current = max(lineage for _, _, _, lineage in entries)
    names_at_current = {name for name, _, _, lineage in entries if lineage == current}

    def short_name(name: str, lineage: int) -> str:
        if lineage == current or name not in names_at_current:
            return name
        return f"{name}.v{lineage}"

    def rank(entry: tuple[str, str, str, int]) -> tuple[int, str]:
        name, _, _, lineage = entry
        if lineage == current:
            return (0, name)
        if name not in names_at_current:
            return (1, name)
        return (2, name)

    return [
        (short_name(name, lineage), file_name, body)
        for name, file_name, body, lineage in sorted(entries, key=rank)
    ]


def raw_string(body: str) -> str:
    """Render `body` as a Rust raw string literal with enough hashes.

    JSON Schema bodies contain `"#/$defs/..."` refs, so `r#"..."#` would
    terminate early; pick the smallest hash count that cannot appear.
    """
    hashes = 1
    while f'"{"#" * hashes}' in body:
        hashes += 1
    pad = "#" * hashes
    return f'r{pad}"{body}"{pad}'


def render() -> str:
    entries = discover()

    lines = [
        "// Code generated by scripts/generate_cli_schemas.py. DO NOT EDIT.",
        "//",
        "// Source: schemas/*.json at the workspace root. Regenerate with:",
        "//   python3 scripts/generate_cli_schemas.py",
        "",
        "/// Short schema names accepted by `h2h schema`, in canonical order.",
        "pub const SCHEMA_NAMES: &[&str] = &[",
    ]

    for name, _file_name, _body in entries:
        lines.append(f"    {json.dumps(name)},")

    lines.extend(
        [
            "];",
            "",
            "/// Published file name for each short schema name.",
            "pub const SCHEMA_FILE_NAMES: &[(&str, &str)] = &[",
        ]
    )

    for name, file_name, _body in entries:
        lines.append(f"    ({json.dumps(name)}, {json.dumps(file_name)}),")

    lines.extend(
        [
            "];",
            "",
            "/// Schema bodies, keyed by short name.",
            "const SCHEMA_BODIES: &[(&str, &str)] = &[",
        ]
    )

    for name, _file_name, body in entries:
        lines.append(f"    (")
        lines.append(f"        {json.dumps(name)},")
        lines.append(f"        {raw_string(body)},")
        lines.append(f"    ),")

    lines.extend(
        [
            "];",
            "",
            "/// Look up a schema body by short name (`core`) or published file",
            "/// name (`hushspec-core.v1.schema.json`); the frozen 0.x lineage is",
            "/// addressed as `core.v0`.",
            "#[must_use]",
            "pub fn schema_body(name: &str) -> Option<&'static str> {",
            "    let short = SCHEMA_FILE_NAMES",
            "        .iter()",
            "        .find(|(_, file)| *file == name)",
            "        .map_or(name, |(short, _)| *short);",
            "    SCHEMA_BODIES",
            "        .iter()",
            "        .find(|(candidate, _)| *candidate == short)",
            "        .map(|(_, body)| *body)",
            "}",
            "",
        ]
    )

    content = "\n".join(lines)

    # Run the output through rustfmt, exactly as generate_sdk_contracts.py does.
    # Without this, `cargo fmt --all` reformats the committed file (long schema
    # file names wrap) and `--check` then reports it as permanently stale.
    rustfmt = shutil.which("rustfmt")
    if rustfmt is None:
        raise SystemExit(
            "rustfmt is not on PATH, and generated_schemas.rs is committed as rustfmt "
            "output. Generating without it would write a file that `cargo fmt` "
            "immediately reformats, which this script's --check then reports "
            "as out of date forever. Install it with `rustup component add "
            "rustfmt`."
        )

    result = subprocess.run(
        [rustfmt, "--emit", "stdout", "--edition", "2024"],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated_schemas.rs is out of date",
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
