#!/usr/bin/env python3
"""Generate the testkit's embedded JSON Schema module from schemas/.

`cargo package` cannot reach files outside the crate directory, so
`hushspec-testkit` cannot `include_str!("../../../schemas/...")` and still be
publishable to crates.io -- exactly the problem `scripts/generate_cli_schemas.py`
solves for the `h2h` binary. This embeds the handful of schemas the conformance
runner validates against in a committed, generated source file.

Only the schemas the testkit actually uses are embedded; the full set lives in
the CLI's module and is served by `h2h schema`.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = ROOT / "schemas"
OUTPUT = ROOT / "crates" / "hushspec-testkit" / "src" / "generated_schemas.rs"

#: (short name, file name) for every schema the testkit validates against.
NEEDED = [
    ("conformance-report", "hushspec-conformance-report.v1.schema.json"),
    ("error-codes", "hushspec-error-codes.v1.schema.json"),
    ("evaluator-test", "hushspec-evaluator-test.v1.schema.json"),
    ("merge-vector", "hushspec-merge-vector.v1.schema.json"),
    ("receipt", "hushspec-receipt.v1.schema.json"),
]


def raw_string(body: str) -> str:
    """Render `body` as a Rust raw string literal with enough hashes.

    JSON Schema bodies contain `"#/$defs/..."` refs, so `r#"..."#` would
    terminate early; pick the smallest hash count that cannot appear.
    """
    hashes = 1
    while f'"{"#" * hashes}' in body:
        hashes += 1
    pad = "#" * hashes
    return f'r{pad}"{body}"{pad}'


def render() -> str:
    lines = [
        "// Code generated by scripts/generate_testkit_schemas.py. DO NOT EDIT.",
        "//",
        "// Source: schemas/*.json at the workspace root. Regenerate with:",
        "//   python3 scripts/generate_testkit_schemas.py",
        "//",
        "// Embedded rather than `include_str!`d because the schemas live outside",
        "// the crate directory and would not survive `cargo package`.",
        "",
        "/// Published file name for each short schema name, in canonical order.",
        "pub const SCHEMA_FILE_NAMES: &[(&str, &str)] = &[",
    ]

    bodies = []
    for name, file_name in NEEDED:
        path = SCHEMAS_DIR / file_name
        if not path.is_file():
            raise SystemExit(f"{path} is missing")
        body = path.read_text()
        json.loads(body)  # a malformed schema fails the generator, not the runner
        lines.append(f"    ({json.dumps(name)}, {json.dumps(file_name)}),")
        bodies.append((name, body))

    lines.extend(["];", "", "/// Schema bodies, keyed by short name.", "const SCHEMA_BODIES: &[(&str, &str)] = &["])
    for name, body in bodies:
        lines.append("    (")
        lines.append(f"        {json.dumps(name)},")
        lines.append(f"        {raw_string(body)},")
        lines.append("    ),")

    lines.extend(
        [
            "];",
            "",
            "/// Look up a schema body by short name (`receipt`) or published file",
            "/// name (`hushspec-receipt.v1.schema.json`).",
            "#[must_use]",
            "pub fn schema_body(name: &str) -> Option<&'static str> {",
            "    let short = SCHEMA_FILE_NAMES",
            "        .iter()",
            "        .find(|(_, file)| *file == name)",
            "        .map_or(name, |(short, _)| *short);",
            "    SCHEMA_BODIES",
            "        .iter()",
            "        .find(|(candidate, _)| *candidate == short)",
            "        .map(|(_, body)| *body)",
            "}",
            "",
        ]
    )

    content = "\n".join(lines)

    rustfmt = shutil.which("rustfmt")
    if rustfmt is None:
        return content

    result = subprocess.run(
        [rustfmt, "--emit", "stdout", "--edition", "2021"],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated module is out of date",
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
