#!/usr/bin/env python3
"""Generate the TypeScript built-in ruleset module from canonical YAML files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RULESETS_DIR = ROOT / "rulesets"
OUTPUT = ROOT / "packages" / "hushspec" / "src" / "builtin.ts"

BUILTIN_NAMES = [
    "default",
    "strict",
    "permissive",
    "ai-agent",
    "cicd",
    "remote-desktop",
]


LIBRARY_DIR = ROOT / "library"


def library_names() -> list[str]:
    """Every vertical-library policy, as `library/<vertical>/<name>`.

    The library ships as built-ins alongside `rulesets/` so that
    `extends: "builtin:library/healthcare/hipaa-base"` resolves with no file
    system, in every SDK. Discovered rather than listed, so adding a policy to
    `library/` is one commit; the `library/` prefix keeps the existing
    `rulesets/` names unchanged.
    """
    return sorted(
        f"library/{path.parent.name}/{path.stem}"
        for path in LIBRARY_DIR.glob("*/*.yaml")
    )


def all_builtin_names() -> list[str]:
    """`rulesets/` first (historical order), then the library."""
    return BUILTIN_NAMES + library_names()


def builtin_yaml(name: str) -> str:
    """The canonical YAML for a built-in name."""
    if name.startswith("library/"):
        return (ROOT / f"{name}.yaml").read_text()
    return (RULESETS_DIR / f"{name}.yaml").read_text()


def render() -> str:
    lines = [
        "// Code generated by scripts/generate_ts_builtins.py. DO NOT EDIT.",
        "",
        "import type { HushSpec } from './schema.js';",
        "import { parseOrThrow } from './parse.js';",
        "",
        "export const BUILTIN_NAMES = [",
    ]

    names = all_builtin_names()

    for name in names:
        lines.append(f"  {json.dumps(name)},")

    lines.extend(
        [
            "] as const;",
            "",
            "export type BuiltinName = (typeof BUILTIN_NAMES)[number];",
            "",
            "const BUILTIN_RULESETS: Record<BuiltinName, string> = {",
        ]
    )

    for name in names:
        lines.append(
            f"  {json.dumps(name)}: {json.dumps(builtin_yaml(name), ensure_ascii=False)},"
        )

    lines.extend(
        [
            "};",
            "",
            "export function loadBuiltin(name: string): HushSpec | null {",
            "  const resolved = name.startsWith('builtin:') ? name.slice(8) : name;",
            "",
            "  if (!(BUILTIN_NAMES as readonly string[]).includes(resolved)) {",
            "    return null;",
            "  }",
            "",
            "  const yaml = BUILTIN_RULESETS[resolved as BuiltinName];",
            "  try {",
            "    return parseOrThrow(yaml);",
            "  } catch {",
            "    return null;",
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if builtin.ts is out of date")
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
