#!/usr/bin/env python3
"""Generate the Go built-in ruleset file from canonical YAML files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RULESETS_DIR = ROOT / "rulesets"
OUTPUT = ROOT / "packages" / "go" / "hushspec" / "builtins.go"

BUILTIN_NAMES = [
    "default",
    "strict",
    "permissive",
    "ai-agent",
    "cicd",
    "remote-desktop",
]


LIBRARY_DIR = ROOT / "library"


def library_names() -> list[str]:
    """Every vertical-library policy, as `library/<vertical>/<name>`.

    The library ships as built-ins alongside `rulesets/` so that
    `extends: "builtin:library/healthcare/hipaa-base"` resolves with no file
    system, in every SDK. Discovered rather than listed, so adding a policy to
    `library/` is one commit; the `library/` prefix keeps the existing
    `rulesets/` names unchanged.
    """
    return sorted(
        f"library/{path.parent.name}/{path.stem}"
        for path in LIBRARY_DIR.glob("*/*.yaml")
    )


def all_builtin_names() -> list[str]:
    """`rulesets/` first (historical order), then the library."""
    return BUILTIN_NAMES + library_names()


def builtin_yaml(name: str) -> str:
    """The canonical YAML for a built-in name."""
    if name.startswith("library/"):
        return (ROOT / f"{name}.yaml").read_text()
    return (RULESETS_DIR / f"{name}.yaml").read_text()


def render() -> str:
    # json.dumps(ensure_ascii=False) produces a double-quoted string escaping
    # only the structural chars (\n \t \r \" \\ and control chars) while
    # emitting any non-ASCII (incl. astral/emoji) as raw UTF-8 -- both are valid
    # in a Go interpreted string literal. (ensure_ascii=True would emit UTF-16
    # surrogate-pair \uXXXX escapes, which Go rejects at compile.)
    lines = [
        "// Code generated by scripts/generate_go_builtins.py. DO NOT EDIT.",
        "",
        "package hushspec",
        "",
        'import "strings"',
        "",
        "var builtinRulesets = map[string]string{",
    ]

    # gofmt aligns the values of consecutive single-line map entries: each key
    # is padded with spaces so every value starts one column past the widest
    # `"key":`. Replicate that here so the output is gofmt-clean without needing
    # gofmt on PATH (the Generated Sources CI job has only Python).
    names = all_builtin_names()
    key_col = {name: len(json.dumps(name)) + 1 for name in names}  # +1 for ':'
    value_col = max(key_col.values()) + 1

    for name in names:
        pad = " " * (value_col - key_col[name])
        lines.append(
            f"\t{json.dumps(name)}:{pad}"
            f"{json.dumps(builtin_yaml(name), ensure_ascii=False)},"
        )

    lines.extend(
        [
            "}",
            "",
            "// BuiltinNames are the canonical names of the embedded policies:",
            '// the rulesets/ presets, then the vertical library as',
            '// "library/<vertical>/<name>".',
            "var BuiltinNames = []string{",
        ]
    )

    for name in names:
        lines.append(f"\t{json.dumps(name)},")

    lines.extend(
        [
            "}",
            "",
            "// LoadBuiltin parses the built-in ruleset for name (with or without the",
            '// "builtin:" prefix) and reports whether the name was found.',
            "func LoadBuiltin(name string) (*HushSpec, bool) {",
            '\tresolved := strings.TrimPrefix(name, "builtin:")',
            "\tyaml, ok := builtinRulesets[resolved]",
            "\tif !ok {",
            "\t\treturn nil, false",
            "\t}",
            "\tspec, err := Parse(yaml)",
            "\tif err != nil {",
            "\t\treturn nil, false",
            "\t}",
            "\treturn spec, true",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if builtins.go is out of date"
    )
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
