// Code generated by scripts/generate_cli_schemas.py. DO NOT EDIT.
//
// Source: schemas/*.json at the workspace root. Regenerate with:
//   python3 scripts/generate_cli_schemas.py

/// Short schema names accepted by `h2h schema`, in canonical order.
pub const SCHEMA_NAMES: &[&str] = &[
    "core",
    "detection",
    "evaluator-test",
    "origins",
    "posture",
    "receipt",
    "signature",
];

/// Published file name for each short schema name.
pub const SCHEMA_FILE_NAMES: &[(&str, &str)] = &[
    ("core", "hushspec-core.v0.schema.json"),
    ("detection", "hushspec-detection.v0.schema.json"),
    ("evaluator-test", "hushspec-evaluator-test.v0.schema.json"),
    ("origins", "hushspec-origins.v0.schema.json"),
    ("posture", "hushspec-posture.v0.schema.json"),
    ("receipt", "hushspec-receipt.v0.schema.json"),
    ("signature", "hushspec-signature.v0.schema.json"),
];

/// Schema bodies, keyed by short name.
const SCHEMA_BODIES: &[(&str, &str)] = &[
    (
        "core",
        r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hushspec.dev/schemas/hushspec-core.v0.schema.json",
  "title": "HushSpec Core v0",
  "description": "Schema for HushSpec Core v0.x documents. Validates portable, engine-neutral AI agent security rules.",
  "type": "object",
  "required": ["hushspec"],
  "additionalProperties": false,
  "properties": {
    "hushspec": {
      "type": "string",
      "pattern": "^0\\.\\d+\\.\\d+$",
      "description": "HushSpec version. Must match ^0\\. for v0.x documents."
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "extends": {
      "type": "string",
      "description": "Reference to a base policy. Resolution is engine-specific."
    },
    "merge_strategy": {
      "type": "string",
      "enum": ["replace", "merge", "deep_merge"],
      "default": "deep_merge",
      "description": "Strategy for merging with the base policy."
    },
    "rules": {
      "$ref": "#/$defs/Rules"
    },
    "extensions": {
      "$ref": "#/$defs/Extensions"
    },
    "metadata": {
      "$ref": "#/$defs/GovernanceMetadata"
    }
  },
  "$defs": {
    "Rules": {
      "type": "object",
      "additionalProperties": false,
      "description": "Security rule declarations.",
      "properties": {
        "forbidden_paths": {
          "$ref": "#/$defs/ForbiddenPaths"
        },
        "path_allowlist": {
          "$ref": "#/$defs/PathAllowlist"
        },
        "egress": {
          "$ref": "#/$defs/Egress"
        },
        "secret_patterns": {
          "$ref": "#/$defs/SecretPatterns"
        },
        "patch_integrity": {
          "$ref": "#/$defs/PatchIntegrity"
        },
        "shell_commands": {
          "$ref": "#/$defs/ShellCommands"
        },
        "tool_access": {
          "$ref": "#/$defs/ToolAccess"
        },
        "computer_use": {
          "$ref": "#/$defs/ComputerUse"
        },
        "remote_desktop_channels": {
          "$ref": "#/$defs/RemoteDesktopChannels"
        },
        "input_injection": {
          "$ref": "#/$defs/InputInjection"
        },
        "browser_automation": {
          "$ref": "#/$defs/BrowserAutomation"
        },
        "code_execution": {
          "$ref": "#/$defs/CodeExecution"
        }
      }
    },
    "ForbiddenPaths": {
      "type": "object",
      "additionalProperties": false,
      "description": "Block access to sensitive filesystem paths.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether this rule is active."
        },
        "patterns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Glob patterns matching forbidden paths."
        },
        "exceptions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Glob patterns that override pattern matches."
        }
      }
    },
    "PathAllowlist": {
      "type": "object",
      "additionalProperties": false,
      "description": "Allowlist-based path access control.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": false,
          "description": "Whether this rule is active."
        },
        "read": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Glob patterns allowed for read access."
        },
        "write": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Glob patterns allowed for write access."
        },
        "patch": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Glob patterns allowed for patch operations. If empty, falls back to write."
        }
      }
    },
    "Egress": {
      "type": "object",
      "additionalProperties": false,
      "description": "Network egress control by domain.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether this rule is active."
        },
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Domain glob patterns to allow."
        },
        "block": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Domain glob patterns to block. Block takes precedence over allow."
        },
        "default": {
          "type": "string",
          "enum": ["allow", "block"],
          "default": "block",
          "description": "Default decision when no pattern matches."
        }
      }
    },
    "SecretPattern": {
      "type": "object",
      "additionalProperties": false,
      "description": "A named regex pattern for secret detection.",
      "required": ["name", "pattern", "severity"],
      "properties": {
        "name": {
          "type": "string",
          "description": "Unique identifier for this pattern."
        },
        "pattern": {
          "type": "string",
          "description": "Regular expression to match against content."
        },
        "severity": {
          "type": "string",
          "enum": ["critical", "error", "warn"],
          "description": "Severity level of a match."
        },
        "description": {
          "type": "string",
          "description": "Human-readable description of what this detects."
        }
      }
    },
    "SecretPatterns": {
      "type": "object",
      "additionalProperties": false,
      "description": "Detect secrets in content.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether this rule is active."
        },
        "patterns": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SecretPattern"
          },
          "default": [],
          "description": "Named regex patterns for secret detection. Names must be unique."
        },
        "skip_paths": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Glob patterns of paths to skip scanning."
        }
      }
    },
    "PatchIntegrity": {
      "type": "object",
      "additionalProperties": false,
      "description": "Validate patch/diff safety.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether this rule is active."
        },
        "max_additions": {
          "type": "integer",
          "minimum": 0,
          "default": 1000,
          "description": "Maximum number of added lines permitted."
        },
        "max_deletions": {
          "type": "integer",
          "minimum": 0,
          "default": 500,
          "description": "Maximum number of deleted lines permitted."
        },
        "forbidden_patterns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Regex patterns forbidden in patch content."
        },
        "require_balance": {
          "type": "boolean",
          "default": false,
          "description": "Whether additions/deletions must be balanced."
        },
        "max_imbalance_ratio": {
          "type": "number",
          "exclusiveMinimum": 0,
          "default": 10.0,
          "description": "Maximum ratio of additions to deletions (or vice versa)."
        }
      }
    },
    "ShellCommands": {
      "type": "object",
      "additionalProperties": false,
      "description": "Block dangerous shell commands.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether this rule is active."
        },
        "forbidden_patterns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Regex patterns forbidden in shell commands."
        }
      }
    },
    "ToolAccess": {
      "type": "object",
      "additionalProperties": false,
      "description": "Control tool/MCP invocations.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether this rule is active."
        },
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Tool name allowlist."
        },
        "block": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Tool name blocklist. Block takes precedence."
        },
        "require_confirmation": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Tools requiring user/operator approval."
        },
        "default": {
          "type": "string",
          "enum": ["allow", "block"],
          "default": "allow",
          "description": "Default decision when no list matches."
        },
        "max_args_size": {
          "type": "integer",
          "minimum": 1,
          "description": "Maximum argument payload size in bytes."
        }
      }
    },
    "ComputerUse": {
      "type": "object",
      "additionalProperties": false,
      "description": "Control computer use agent actions.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": false,
          "description": "Whether this rule is active."
        },
        "mode": {
          "type": "string",
          "enum": ["observe", "guardrail", "fail_closed"],
          "default": "guardrail",
          "description": "Enforcement mode."
        },
        "allowed_actions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Action identifiers permitted (e.g., 'remote.session.connect', 'input.inject')."
        }
      }
    },
    "RemoteDesktopChannels": {
      "type": "object",
      "additionalProperties": false,
      "description": "Control remote desktop side channels.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": false,
          "description": "Whether this rule is active."
        },
        "clipboard": {
          "type": "boolean",
          "default": false,
          "description": "Allow clipboard sharing."
        },
        "file_transfer": {
          "type": "boolean",
          "default": false,
          "description": "Allow file transfer."
        },
        "audio": {
          "type": "boolean",
          "default": true,
          "description": "Allow audio redirection."
        },
        "drive_mapping": {
          "type": "boolean",
          "default": false,
          "description": "Allow drive/filesystem mapping."
        }
      }
    },
    "InputInjection": {
      "type": "object",
      "additionalProperties": false,
      "description": "Control input injection capabilities.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": false,
          "description": "Whether this rule is active."
        },
        "allowed_types": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Input type identifiers permitted (e.g., 'keyboard', 'mouse', 'touch')."
        },
        "require_postcondition_probe": {
          "type": "boolean",
          "default": false,
          "description": "Whether postcondition verification is required after input injection."
        }
      }
    },
    "BrowserAutomation": {
      "type": "object",
      "additionalProperties": false,
      "description": "Fine-grained controls for browser-automation tool calls: domain allowlist, verb allowlist, and credential detection in type actions.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": false,
          "description": "Whether this rule is active."
        },
        "allowed_domains": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Hosts the agent may navigate to. Supports exact match and *.suffix wildcards."
        },
        "blocked_domains": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Hosts that are always denied (evaluated before the allowlist)."
        },
        "allowed_verbs": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Verbs (actions) the agent may issue. Empty means any verb."
        },
        "credential_detection": {
          "type": "boolean",
          "default": true,
          "description": "Check type/input action values for credential-shaped secrets."
        },
        "extra_credential_patterns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Extra credential regex patterns layered on top of the built-in detectors."
        }
      }
    },
    "CodeExecution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Restrictions for sandboxed interpreter actions: language allowlist, dangerous module denylist, network gating, and execution-time bounds.",
      "properties": {
        "when": {
          "$ref": "#/$defs/Condition",
          "description": "Condition gating whether this block is active (core spec 3.13)."
        },
        "enabled": {
          "type": "boolean",
          "default": false,
          "description": "Whether this rule is active."
        },
        "language_allowlist": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Allowed interpreter languages (e.g. python, javascript). Empty means any language."
        },
        "module_denylist": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": [],
          "description": "Module names whose imports or uses in the code body are denied (word-boundary literal matches)."
        },
        "network_access": {
          "type": "boolean",
          "default": false,
          "description": "Permit code-execution calls that request network access."
        },
        "max_execution_time_ms": {
          "type": "integer",
          "minimum": 0,
          "description": "Maximum execution time in milliseconds."
        },
        "max_scan_bytes": {
          "type": "integer",
          "minimum": 1,
          "description": "Maximum bytes of code to scan for module detection."
        }
      }
    },
    "Condition": {
      "type": "object",
      "additionalProperties": false,
      "description": "Conditional rule-block gate (core spec 3.13). Present fields are combined with AND. Parsers MUST also reject nesting deeper than 8 levels.",
      "properties": {
        "time_window": {
          "$ref": "#/$defs/TimeWindow"
        },
        "context": {
          "type": "object",
          "additionalProperties": true,
          "description": "Dot-delimited runtime-context paths that must equal the given values (JSON equality)."
        },
        "all_of": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Condition"
          },
          "description": "Every sub-condition must hold."
        },
        "any_of": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Condition"
          },
          "description": "At least one sub-condition must hold; an empty array is treated as absent."
        },
        "not": {
          "$ref": "#/$defs/Condition",
          "description": "The sub-condition must not hold."
        }
      }
    },
    "TimeWindow": {
      "type": "object",
      "additionalProperties": false,
      "required": ["start", "end"],
      "description": "Daily time window; half-open [start, end), wrapping midnight when start > end.",
      "properties": {
        "start": {
          "type": "string",
          "pattern": "^([01][0-9]|2[0-3]):[0-5][0-9]$",
          "description": "Window start, HH:MM 24-hour."
        },
        "end": {
          "type": "string",
          "pattern": "^([01][0-9]|2[0-3]):[0-5][0-9]$",
          "description": "Window end, HH:MM 24-hour."
        },
        "timezone": {
          "type": "string",
          "default": "UTC",
          "description": "IANA time zone identifier or fixed offset (+HH:MM / -HH:MM)."
        },
        "days": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^([Mm][Oo][Nn]|[Tt][Uu][Ee]|[Ww][Ee][Dd]|[Tt][Hh][Uu]|[Ff][Rr][Ii]|[Ss][Aa][Tt]|[Ss][Uu][Nn])$"
          },
          "description": "Days on which the window applies (case-insensitive abbreviations); defaults to all days."
        }
      }
    },
    "Extensions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Extension modules for optional capabilities beyond core rules.",
      "properties": {
        "posture": {
          "type": "object",
          "description": "Stateful capability and budget management. Schema defined in companion specification."
        },
        "origins": {
          "type": "object",
          "description": "Origin-aware policy profiles. Schema defined in companion specification."
        },
        "detection": {
          "type": "object",
          "description": "Detection engine thresholds and configuration. Schema defined in companion specification."
        }
      }
    },
    "GovernanceMetadata": {
      "type": "object",
      "additionalProperties": false,
      "description": "Optional governance metadata for enterprise policy lifecycle management. Has no impact on evaluation.",
      "properties": {
        "author": {
          "type": "string",
          "description": "Identity of the policy author (e.g., email, team name)."
        },
        "approved_by": {
          "type": "string",
          "description": "Identity of the policy approver."
        },
        "approval_date": {
          "type": "string",
          "description": "ISO 8601 date when the policy was approved."
        },
        "classification": {
          "type": "string",
          "enum": ["public", "internal", "confidential", "restricted"],
          "description": "Data classification level of the policy."
        },
        "change_ticket": {
          "type": "string",
          "description": "Change management reference (e.g., JIRA ticket, ServiceNow ID)."
        },
        "lifecycle_state": {
          "type": "string",
          "enum": ["draft", "review", "approved", "deployed", "deprecated", "archived"],
          "description": "Current lifecycle state of the policy."
        },
        "policy_version": {
          "type": "integer",
          "minimum": 1,
          "description": "Monotonically increasing policy version counter."
        },
        "effective_date": {
          "type": "string",
          "description": "ISO 8601 date when the policy becomes effective."
        },
        "expiry_date": {
          "type": "string",
          "description": "ISO 8601 date when the policy expires."
        }
      }
    }
  }
}
"##,
    ),
    (
        "detection",
        r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hushspec.dev/schemas/hushspec-detection.v0.schema.json",
  "title": "HushSpec Detection Extension v0",
  "description": "Schema for the HushSpec Detection extension. Declares thresholds and configuration for content analysis guards.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "prompt_injection": {
      "$ref": "#/$defs/PromptInjectionDetection"
    },
    "jailbreak": {
      "$ref": "#/$defs/JailbreakDetection"
    },
    "threat_intel": {
      "$ref": "#/$defs/ThreatIntelDetection"
    }
  },
  "$defs": {
    "Level": {
      "type": "string",
      "enum": ["safe", "suspicious", "high", "critical"],
      "description": "Detection severity level, ordered: safe < suspicious < high < critical."
    },
    "PromptInjectionDetection": {
      "type": "object",
      "additionalProperties": false,
      "description": "Configuration for prompt injection detection.",
      "properties": {
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether prompt injection detection is active."
        },
        "warn_at_or_above": {
          "$ref": "#/$defs/Level",
          "default": "suspicious",
          "description": "Minimum detection level that produces a warning."
        },
        "block_at_or_above": {
          "$ref": "#/$defs/Level",
          "default": "high",
          "description": "Minimum detection level that produces a denial."
        },
        "max_scan_bytes": {
          "type": "integer",
          "minimum": 1,
          "default": 200000,
          "description": "Maximum input size to scan, in bytes."
        }
      }
    },
    "JailbreakDetection": {
      "type": "object",
      "additionalProperties": false,
      "description": "Configuration for jailbreak detection.",
      "properties": {
        "enabled": {
          "type": "boolean",
          "default": true,
          "description": "Whether jailbreak detection is active."
        },
        "block_threshold": {
          "type": "integer",
          "minimum": 0,
          "maximum": 100,
          "default": 80,
          "description": "Risk score (0-100) at or above which input is denied."
        },
        "warn_threshold": {
          "type": "integer",
          "minimum": 0,
          "maximum": 100,
          "default": 50,
          "description": "Risk score (0-100) at or above which a warning is produced."
        },
        "max_input_bytes": {
          "type": "integer",
          "minimum": 1,
          "default": 200000,
          "description": "Maximum input size to scan, in bytes."
        }
      }
    },
    "ThreatIntelDetection": {
      "type": "object",
      "additionalProperties": false,
      "description": "Configuration for threat intelligence screening.",
      "properties": {
        "enabled": {
          "type": "boolean",
          "default": false,
          "description": "Whether threat intelligence screening is active."
        },
        "pattern_db": {
          "type": "string",
          "description": "Path to pattern database file or \"builtin:<name>\" for engine-bundled databases."
        },
        "similarity_threshold": {
          "type": "number",
          "minimum": 0.0,
          "maximum": 1.0,
          "default": 0.7,
          "description": "Minimum similarity score (0.0-1.0) for a pattern match to be considered a finding."
        },
        "top_k": {
          "type": "integer",
          "minimum": 1,
          "default": 5,
          "description": "Number of top matches to include in evaluation evidence."
        }
      }
    }
  }
}
"##,
    ),
    (
        "evaluator-test",
        r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hushspec.dev/schemas/hushspec-evaluator-test.v0.schema.json",
  "title": "HushSpec Evaluator Fixture v0",
  "description": "Schema for versioned evaluator fixtures used by the HushSpec reference evaluator and conformance testkit.",
  "type": "object",
  "required": ["hushspec_test", "description", "policy", "cases"],
  "additionalProperties": false,
  "properties": {
    "hushspec_test": {
      "type": "string",
      "pattern": "^0\\.\\d+\\.\\d+$",
      "description": "Fixture format version."
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "policy": {
      "type": "object",
      "required": ["hushspec"],
      "description": "Embedded HushSpec document. Full policy validation is performed separately by the SDK.",
      "additionalProperties": true
    },
    "cases": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/EvaluationCase"
      }
    }
  },
  "$defs": {
    "EvaluationCase": {
      "type": "object",
      "required": ["description", "action", "expect"],
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "$ref": "#/$defs/Action"
        },
        "context": {
          "$ref": "#/$defs/RuntimeContext"
        },
        "expect": {
          "$ref": "#/$defs/ExpectedResult"
        }
      }
    },
    "RuntimeContext": {
      "type": "object",
      "additionalProperties": false,
      "description": "Runtime context supplied to `when` conditions (core spec 3.13).",
      "properties": {
        "user": { "type": "object", "additionalProperties": true },
        "environment": { "type": "string" },
        "deployment": { "type": "object", "additionalProperties": true },
        "agent": { "type": "object", "additionalProperties": true },
        "session": { "type": "object", "additionalProperties": true },
        "request": { "type": "object", "additionalProperties": true },
        "custom": { "type": "object", "additionalProperties": true },
        "current_time": {
          "type": "string",
          "description": "RFC 3339 timestamp used instead of the engine clock (deterministic testing)."
        }
      }
    },
    "Action": {
      "type": "object",
      "required": ["type"],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "description": "Action type (core spec 5). Any string is accepted so that unknown-type vectors can assert the fail-closed deny; reference types are file_read, file_write, patch_apply, shell_command, tool_call, egress, computer_use, input_inject, browser_action, code_exec, custom."
        },
        "target": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "args_size": {
          "type": "integer",
          "minimum": 0
        },
        "origin": {
          "$ref": "#/$defs/Origin"
        },
        "posture": {
          "$ref": "#/$defs/PostureInput"
        },
        "url": {
          "type": "string",
          "description": "browser_action: navigation destination (core spec 3.11)."
        },
        "network": {
          "type": "boolean",
          "description": "code_exec: whether the call requests network access (core spec 3.12)."
        },
        "timeout_ms": {
          "type": "integer",
          "minimum": 0,
          "description": "code_exec: requested execution time in milliseconds (core spec 3.12)."
        }
      }
    },
    "Origin": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "provider": { "type": "string" },
        "tenant_id": { "type": "string" },
        "space_id": { "type": "string" },
        "space_type": { "type": "string" },
        "visibility": { "type": "string" },
        "external_participants": { "type": "boolean" },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        },
        "sensitivity": { "type": "string" },
        "actor_role": { "type": "string" }
      }
    },
    "PostureInput": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "current": { "type": "string" },
        "signal": { "type": "string" }
      }
    },
    "ExpectedResult": {
      "type": "object",
      "required": ["decision"],
      "additionalProperties": false,
      "properties": {
        "decision": {
          "type": "string",
          "enum": ["allow", "warn", "deny"]
        },
        "matched_rule": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "origin_profile": {
          "type": "string"
        },
        "posture": {
          "$ref": "#/$defs/PostureResult"
        }
      }
    },
    "PostureResult": {
      "type": "object",
      "required": ["current", "next"],
      "additionalProperties": false,
      "properties": {
        "current": { "type": "string" },
        "next": { "type": "string" }
      }
    }
  }
}
"##,
    ),
    (
        "origins",
        r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hushspec.dev/schemas/hushspec-origins.v0.schema.json",
  "title": "HushSpec Origins Extension v0",
  "description": "Schema for the HushSpec Origins extension. Declares origin-aware policy projection for multi-source agent workflows.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "default_behavior": {
      "type": "string",
      "enum": ["deny", "minimal_profile"],
      "default": "deny",
      "description": "Behavior when no profile matches. \"deny\" blocks unmatched origins; \"minimal_profile\" proceeds under base policy."
    },
    "profiles": {
      "type": "array",
      "description": "Origin profiles, each with match criteria and policy overrides.",
      "items": {
        "$ref": "#/$defs/OriginProfile"
      }
    }
  },
  "$defs": {
    "OriginProfile": {
      "type": "object",
      "required": ["id"],
      "additionalProperties": false,
      "description": "An origin profile that narrows the base policy for matching requests.",
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier for this profile."
        },
        "match": {
          "$ref": "#/$defs/OriginMatch"
        },
        "posture": {
          "type": "string",
          "description": "Initial posture state for this origin. Must reference a state in extensions.posture.states."
        },
        "tool_access": {
          "$ref": "#/$defs/ToolAccessRule"
        },
        "egress": {
          "$ref": "#/$defs/EgressRule"
        },
        "data": {
          "$ref": "#/$defs/DataPolicy"
        },
        "budgets": {
          "$ref": "#/$defs/OriginBudgets"
        },
        "bridge": {
          "$ref": "#/$defs/BridgePolicy"
        },
        "explanation": {
          "type": "string"
        }
      }
    },
    "OriginMatch": {
      "type": "object",
      "additionalProperties": false,
      "description": "Criteria for matching an incoming request to this profile.",
      "properties": {
        "provider": {
          "type": "string",
          "description": "Source provider. Standard values: slack, teams, github, jira, email, discord, webhook, custom."
        },
        "tenant_id": {
          "type": "string",
          "description": "Tenant or workspace identifier."
        },
        "space_id": {
          "type": "string",
          "description": "Channel, room, or repository identifier. Highest priority match field."
        },
        "space_type": {
          "type": "string",
          "enum": [
            "channel",
            "group",
            "dm",
            "thread",
            "issue",
            "ticket",
            "pull_request",
            "email_thread"
          ],
          "description": "Type of space the request originated from."
        },
        "visibility": {
          "type": "string",
          "enum": [
            "private",
            "internal",
            "public",
            "external_shared"
          ],
          "description": "Visibility level of the source space."
        },
        "external_participants": {
          "type": "boolean",
          "description": "Whether external participants are present in the source space."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Tags that must ALL be present on the source (AND semantics)."
        },
        "sensitivity": {
          "type": "string",
          "description": "Sensitivity classification of the source context."
        },
        "actor_role": {
          "type": "string",
          "description": "Role of the requesting actor (e.g., admin, member, guest)."
        }
      }
    },
    "ToolAccessRule": {
      "type": "object",
      "additionalProperties": false,
      "description": "Tool access overrides for this origin. Composes with base rules.tool_access via intersection (allow) and union (block).",
      "properties": {
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Tool name allowlist. Intersected with base allowlist."
        },
        "block": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Tool name blocklist. Unioned with base blocklist."
        },
        "require_confirmation": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Tools requiring user/operator approval. Unioned with base list."
        },
        "default": {
          "type": "string",
          "enum": ["allow", "block"],
          "description": "Default decision. If either base or origin specifies \"block\", effective default is \"block\"."
        },
        "max_args_size": {
          "type": "integer",
          "minimum": 1,
          "description": "Maximum argument payload size in bytes. The smaller of base and origin applies."
        }
      }
    },
    "EgressRule": {
      "type": "object",
      "additionalProperties": false,
      "description": "Egress overrides for this origin. Composes with base rules.egress via intersection (allow) and union (block).",
      "properties": {
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Domain allowlist. Intersected with base allowlist."
        },
        "block": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Domain blocklist. Unioned with base blocklist."
        },
        "default": {
          "type": "string",
          "enum": ["allow", "block"],
          "description": "Default decision. If either base or origin specifies \"block\", effective default is \"block\"."
        }
      }
    },
    "DataPolicy": {
      "type": "object",
      "additionalProperties": false,
      "description": "Data handling controls for this origin context.",
      "properties": {
        "allow_external_sharing": {
          "type": "boolean",
          "default": false,
          "description": "Whether content may be shared outside the origin context."
        },
        "redact_before_send": {
          "type": "boolean",
          "default": false,
          "description": "Whether sensitive content must be redacted before output."
        },
        "block_sensitive_outputs": {
          "type": "boolean",
          "default": false,
          "description": "Whether outputs containing sensitive patterns are blocked."
        }
      }
    },
    "OriginBudgets": {
      "type": "object",
      "additionalProperties": false,
      "description": "Budget overrides for this origin. The smaller of base and origin values applies.",
      "properties": {
        "tool_calls": {
          "type": "integer",
          "minimum": 0,
          "description": "Maximum number of tool/MCP invocations."
        },
        "egress_calls": {
          "type": "integer",
          "minimum": 0,
          "description": "Maximum number of outbound network requests."
        },
        "shell_commands": {
          "type": "integer",
          "minimum": 0,
          "description": "Maximum number of shell command executions."
        }
      }
    },
    "BridgePolicy": {
      "type": "object",
      "additionalProperties": false,
      "description": "Controls for cross-origin data flow.",
      "properties": {
        "allow_cross_origin": {
          "type": "boolean",
          "default": false,
          "description": "Whether cross-origin data flow is permitted."
        },
        "allowed_targets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/BridgeTarget"
          },
          "description": "Specific destinations permitted for cross-origin data flow."
        },
        "require_approval": {
          "type": "boolean",
          "default": false,
          "description": "Whether cross-origin flows require user/operator approval."
        }
      }
    },
    "BridgeTarget": {
      "type": "object",
      "additionalProperties": false,
      "description": "A permitted destination for cross-origin data flow.",
      "properties": {
        "provider": {
          "type": "string",
          "description": "Target provider."
        },
        "space_type": {
          "type": "string",
          "enum": [
            "channel",
            "group",
            "dm",
            "thread",
            "issue",
            "ticket",
            "pull_request",
            "email_thread"
          ],
          "description": "Target space type."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Required tags on the target (AND semantics)."
        },
        "visibility": {
          "type": "string",
          "enum": [
            "private",
            "internal",
            "public",
            "external_shared"
          ],
          "description": "Required visibility level of the target."
        }
      }
    }
  }
}
"##,
    ),
    (
        "posture",
        r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hushspec.dev/schemas/hushspec-posture.v0.schema.json",
  "title": "HushSpec Posture Extension v0",
  "description": "Schema for the HushSpec Posture extension. Declares a state machine for capability and budget management.",
  "type": "object",
  "required": ["initial", "states", "transitions"],
  "additionalProperties": false,
  "properties": {
    "initial": {
      "type": "string",
      "description": "Initial state name. Must reference a key in states."
    },
    "states": {
      "type": "object",
      "description": "Named states in the posture state machine.",
      "minProperties": 1,
      "additionalProperties": {
        "$ref": "#/$defs/PostureState"
      }
    },
    "transitions": {
      "type": "array",
      "description": "Transitions between states, triggered by events.",
      "items": {
        "$ref": "#/$defs/PostureTransition"
      }
    }
  },
  "$defs": {
    "PostureState": {
      "type": "object",
      "additionalProperties": false,
      "description": "A named state in the posture state machine.",
      "properties": {
        "description": {
          "type": "string"
        },
        "capabilities": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Capability identifiers available in this state. Standard values: file_access, file_write, egress, shell, tool_call, patch, custom."
        },
        "budgets": {
          "type": "object",
          "description": "Budget limits keyed by budget key. Standard keys: file_writes, egress_calls, shell_commands, tool_calls, patches, custom_calls.",
          "additionalProperties": {
            "type": "integer",
            "minimum": 0
          }
        }
      }
    },
    "PostureTransition": {
      "type": "object",
      "required": ["from", "to", "on"],
      "additionalProperties": false,
      "description": "A transition between posture states.",
      "properties": {
        "from": {
          "type": "string",
          "description": "Source state name, or \"*\" to match any state."
        },
        "to": {
          "type": "string",
          "not": {
            "const": "*"
          },
          "description": "Target state name. Must not be \"*\"."
        },
        "on": {
          "type": "string",
          "enum": [
            "user_approval",
            "user_denial",
            "critical_violation",
            "any_violation",
            "timeout",
            "budget_exhausted",
            "pattern_match"
          ],
          "description": "Trigger that causes this transition."
        },
        "after": {
          "type": "string",
          "pattern": "^\\d+[smhd]$",
          "description": "Duration string. Required when trigger is \"timeout\". Format: <number><unit> where unit is s, m, h, or d."
        }
      },
      "if": {
        "properties": {
          "on": {
            "const": "timeout"
          }
        },
        "required": ["on"]
      },
      "then": {
        "required": ["from", "to", "on", "after"]
      }
    }
  }
}
"##,
    ),
    (
        "receipt",
        r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hushspec.dev/schemas/hushspec-receipt.v0.schema.json",
  "title": "HushSpec Decision Receipt v0",
  "description": "A self-contained record of a single HushSpec policy evaluation decision. Receipts capture the full context of an evaluation: the action that was evaluated, the decision that was reached, the rule trace showing every rule block consulted, and the policy identity.",
  "type": "object",
  "required": [
    "receipt_id",
    "timestamp",
    "hushspec_version",
    "action",
    "decision",
    "rule_trace",
    "policy",
    "evaluation_duration_us"
  ],
  "additionalProperties": false,
  "properties": {
    "receipt_id": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
      "description": "Unique identifier for this receipt (UUID v4)."
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "ISO 8601 timestamp of when the evaluation occurred, with UTC timezone (Z suffix)."
    },
    "hushspec_version": {
      "type": "string",
      "description": "The HushSpec specification version used for evaluation."
    },
    "action": {
      "$ref": "#/$defs/ActionSummary"
    },
    "decision": {
      "type": "string",
      "enum": ["allow", "warn", "deny"],
      "description": "The final evaluation decision: allow, warn, or deny."
    },
    "matched_rule": {
      "type": ["string", "null"],
      "default": null,
      "description": "The rule path that determined the final decision (e.g., 'rules.tool_access.block'). Null when no specific rule matched."
    },
    "reason": {
      "type": ["string", "null"],
      "default": null,
      "description": "Human-readable explanation of why the decision was reached."
    },
    "rule_trace": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/RuleEvaluation"
      },
      "description": "Ordered trace of every rule block consulted during evaluation. Includes rules that were skipped due to short-circuiting."
    },
    "policy": {
      "$ref": "#/$defs/PolicySummary"
    },
    "origin_profile": {
      "type": ["string", "null"],
      "default": null,
      "description": "The ID of the origin profile that was selected during evaluation, if any."
    },
    "posture": {
      "oneOf": [
        { "$ref": "#/$defs/PostureResult" },
        { "type": "null" }
      ],
      "default": null,
      "description": "Posture state information, including current state and next state after any signal-triggered transition."
    },
    "enforcement": {
      "oneOf": [
        { "$ref": "#/$defs/EnforcementSummary" },
        { "type": "null" }
      ],
      "default": null,
      "description": "How the runtime applied this decision, when the evaluation was performed by an enforcement point (e.g. HushGuard). Null/absent for pure evaluations. The 'decision' field always records the evaluated policy decision; this object records what the runtime did with it."
    },
    "evaluation_duration_us": {
      "type": "integer",
      "minimum": 0,
      "description": "Wall-clock evaluation time in microseconds. Excludes receipt construction and serialization time."
    }
  },
  "$defs": {
    "ActionSummary": {
      "type": "object",
      "required": ["type"],
      "additionalProperties": false,
      "description": "Summary of the evaluated action. Content is never included directly; only a hash is recorded to prevent accidental logging of sensitive data.",
      "properties": {
        "type": {
          "type": "string",
          "description": "The action type that was evaluated (e.g., 'tool_call', 'egress', 'file_read')."
        },
        "target": {
          "type": ["string", "null"],
          "default": null,
          "description": "The target of the action (tool name, URL, file path, etc.). Null when not applicable."
        },
        "content_redacted": {
          "type": "boolean",
          "default": false,
          "description": "True when action content was present but omitted from the receipt for privacy."
        }
      }
    },
    "RuleEvaluation": {
      "type": "object",
      "required": ["rule_block", "outcome", "evaluated"],
      "additionalProperties": false,
      "description": "Record of a single rule block evaluation during the decision process.",
      "properties": {
        "rule_block": {
          "type": "string",
          "description": "The rule block that was consulted (e.g., 'rules.forbidden_paths', 'rules.tool_access.block')."
        },
        "outcome": {
          "type": "string",
          "enum": ["allow", "warn", "deny", "skip"],
          "description": "The outcome of this rule evaluation. 'skip' indicates the rule was not evaluated (disabled, not applicable, or short-circuited)."
        },
        "matched_rule": {
          "type": ["string", "null"],
          "default": null,
          "description": "The specific rule path that produced this outcome, if any."
        },
        "reason": {
          "type": ["string", "null"],
          "default": null,
          "description": "Human-readable explanation of why this rule produced this outcome."
        },
        "evaluated": {
          "type": "boolean",
          "description": "Whether the rule block was actually evaluated. False if the rule was short-circuited by a prior decision or is not applicable to the action type."
        }
      }
    },
    "PolicySummary": {
      "type": "object",
      "required": ["version"],
      "additionalProperties": false,
      "description": "Identity and integrity summary of the policy document used during evaluation.",
      "properties": {
        "name": {
          "type": ["string", "null"],
          "default": null,
          "description": "The name field from the policy document, if present."
        },
        "version": {
          "type": "string",
          "description": "The hushspec version field from the policy document."
        },
        "content_hash": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$",
          "description": "SHA-256 hex digest of the canonical JSON serialization of the resolved policy document. Omitted entirely when the evaluation ran with audit disabled -- the zero-overhead disabled-audit fast path never computes a hash, so the field is absent rather than an empty string."
        }
      }
    },
    "PostureResult": {
      "type": "object",
      "required": ["current", "next"],
      "additionalProperties": false,
      "description": "Posture state at evaluation time and after any signal-triggered transition.",
      "properties": {
        "current": {
          "type": "string",
          "description": "The posture state that was active during evaluation."
        },
        "next": {
          "type": "string",
          "description": "The posture state after any signal-triggered transition. Same as current if no transition occurred."
        }
      }
    },
    "EnforcementSummary": {
      "type": "object",
      "required": ["mode", "outcome"],
      "additionalProperties": false,
      "description": "Runtime enforcement disposition for a single decision.",
      "properties": {
        "mode": {
          "type": "string",
          "enum": ["enforce", "monitor"],
          "description": "Effective enforcement mode after per-rule overrides and panic resolution."
        },
        "outcome": {
          "type": "string",
          "enum": ["allowed", "confirmed", "blocked", "would_block"],
          "description": "What happened at the tool boundary: allowed (action proceeded), confirmed (warn approved via confirmation handler), blocked (execution prevented), would_block (monitor mode let a warn/deny proceed)."
        }
      }
    }
  }
}
"##,
    ),
    (
        "signature",
        r#"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hushspec.dev/schemas/hushspec-signature.v0.schema.json",
  "title": "HushSpec Detached Policy Signature v0",
  "description": "A detached cryptographic signature for a HushSpec policy document. Stored as a .sig JSON file alongside the signed policy file.",
  "type": "object",
  "required": ["format_version", "algorithm", "content_hash", "signature", "signed_at", "key_id"],
  "additionalProperties": false,
  "properties": {
    "format_version": {
      "type": "string",
      "const": "0.1.0",
      "description": "Signature format version."
    },
    "algorithm": {
      "type": "string",
      "enum": ["ed25519"],
      "description": "Signature algorithm. Must be 'ed25519' for v0.x."
    },
    "content_hash": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$",
      "description": "SHA-256 hex digest of the raw policy file bytes."
    },
    "signature": {
      "type": "string",
      "description": "Base64-encoded Ed25519 signature of the canonical signature envelope, including content_hash, signed_at, key_id, and signer when present."
    },
    "signed_at": {
      "type": "string",
      "format": "date-time",
      "description": "ISO 8601 UTC timestamp of when the signature was created."
    },
    "key_id": {
      "type": "string",
      "minLength": 1,
      "description": "Opaque identifier for the signing key, used for key lookup."
    },
    "signer": {
      "type": "string",
      "description": "Human-readable identity of the signer (email, team name, etc.)."
    }
  }
}
"#,
    ),
];

/// Look up a schema body by short name (`core`) or published file
/// name (`hushspec-core.v0.schema.json`).
#[must_use]
pub fn schema_body(name: &str) -> Option<&'static str> {
    let short = SCHEMA_FILE_NAMES
        .iter()
        .find(|(_, file)| *file == name)
        .map_or(name, |(short, _)| *short);
    SCHEMA_BODIES
        .iter()
        .find(|(candidate, _)| *candidate == short)
        .map(|(_, body)| *body)
}
