// Code generated by scripts/generate_cli_frameworks.py. DO NOT EDIT.
//
// Source: spec/registries/frameworks.yaml. Regenerate with:
//   python3 scripts/generate_cli_frameworks.py

/// One registered compliance framework (spec/registries/frameworks.yaml).
#[derive(Clone, Copy, Debug, serde::Serialize)]
pub struct Framework {
    /// Registry id, as named by `metadata.controls[].framework`.
    pub id: &'static str,
    /// Human-readable framework name.
    pub name: &'static str,
    /// Edition, revision, or publication year the control ids refer to.
    pub version: &'static str,
    /// Canonical location of the framework text.
    pub url: &'static str,
    /// Anchored regex every `control_id` for this framework must match.
    pub control_id_pattern: &'static str,
}

/// Version of the registry file this table was generated from.
pub const REGISTRY_VERSION: &str = "0.1.0";

/// Registered frameworks, sorted by id.
pub const FRAMEWORKS: &[Framework] = &[
    Framework {
        id: "ferpa",
        name: "Family Educational Rights and Privacy Act",
        version: "34 CFR Part 99",
        url: "https://www.ecfr.gov/current/title-34/subtitle-A/part-99",
        control_id_pattern: "^99\\.[0-9]{1,2}(\\([a-z0-9]+\\))*$",
    },
    Framework {
        id: "hipaa-2013",
        name: "HIPAA Security and Privacy Rules",
        version: "2013 Omnibus Rule (45 CFR Part 164)",
        url: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164",
        control_id_pattern: "^164\\.[0-9]{3}(\\([a-z]\\))?(\\([0-9]+\\))?(\\([ivxlc]+\\))?(\\([A-Z]\\))?$",
    },
    Framework {
        id: "iso-27001-2022",
        name: "ISO/IEC 27001 Annex A",
        version: "2022",
        url: "https://www.iso.org/standard/27001",
        control_id_pattern: "^A\\.[0-9]{1,2}\\.[0-9]{1,2}$",
    },
    Framework {
        id: "nist-800-53-r5",
        name: "NIST SP 800-53 Security and Privacy Controls",
        version: "Revision 5",
        url: "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final",
        control_id_pattern: "^[A-Z]{2}-[0-9]{1,2}(\\([0-9]{1,2}\\))?$",
    },
    Framework {
        id: "nist-ai-rmf-1.0",
        name: "NIST AI Risk Management Framework",
        version: "1.0",
        url: "https://www.nist.gov/itl/ai-risk-management-framework",
        control_id_pattern: "^(GOVERN|MAP|MEASURE|MANAGE) [0-9]{1,2}\\.[0-9]{1,2}$",
    },
    Framework {
        id: "owasp-llm-top10-2025",
        name: "OWASP Top 10 for Large Language Model Applications",
        version: "2025",
        url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
        control_id_pattern: "^LLM[0-9]{2}$",
    },
    Framework {
        id: "pci-dss-4.0",
        name: "Payment Card Industry Data Security Standard",
        version: "4.0",
        url: "https://www.pcisecuritystandards.org/document_library/",
        control_id_pattern: "^(Req )?[0-9]{1,2}(\\.[0-9]{1,2}){0,2}$",
    },
    Framework {
        id: "soc2-tsc-2017",
        name: "AICPA SOC 2 Trust Services Criteria",
        version: "2017 (with 2022 revised points of focus)",
        url: "https://www.aicpa-cima.com/resources/landing/system-and-organization-controls-soc-suite-of-services",
        control_id_pattern: "^(CC|A|C|PI|P)[0-9]{1,2}\\.[0-9]{1,2}$",
    },
];

/// Look up a registered framework by id.
#[must_use]
pub fn framework(id: &str) -> Option<&'static Framework> {
    FRAMEWORKS.iter().find(|entry| entry.id == id)
}
