// Code generated by scripts/generate_sdk_contracts.py. DO NOT EDIT.

package hushspec

var RuleKeys = map[string]struct{}{
	"forbidden_paths":         {},
	"path_allowlist":          {},
	"egress":                  {},
	"secret_patterns":         {},
	"patch_integrity":         {},
	"shell_commands":          {},
	"tool_access":             {},
	"computer_use":            {},
	"remote_desktop_channels": {},
	"input_injection":         {},
	"browser_automation":      {},
	"code_execution":          {},
}

var ExtensionKeys = map[string]struct{}{
	"posture":   {},
	"origins":   {},
	"detection": {},
}

var ControlMappingKeys = map[string]struct{}{
	"framework":  {},
	"control_id": {},
	"rule_paths": {},
	"notes":      {},
}

var ChangelogEntryKeys = map[string]struct{}{
	"version": {},
	"date":    {},
	"summary": {},
	"author":  {},
}

var RateConditionKeys = map[string]struct{}{
	"counter":    {},
	"threshold":  {},
	"comparison": {},
}

var MergeStrategies = map[MergeStrategy]struct{}{
	MergeStrategy("replace"):    {},
	MergeStrategy("merge"):      {},
	MergeStrategy("deep_merge"): {},
}

var DefaultActions = map[DefaultAction]struct{}{
	DefaultAction("allow"): {},
	DefaultAction("block"): {},
}

var Severities = map[string]struct{}{
	"critical": {},
	"error":    {},
	"warn":     {},
}

var ComputerUseModes = map[ComputerUseMode]struct{}{
	ComputerUseMode("observe"):     {},
	ComputerUseMode("guardrail"):   {},
	ComputerUseMode("fail_closed"): {},
}

var TransitionTriggers = map[TransitionTrigger]struct{}{
	TransitionTrigger("user_approval"):      {},
	TransitionTrigger("user_denial"):        {},
	TransitionTrigger("critical_violation"): {},
	TransitionTrigger("any_violation"):      {},
	TransitionTrigger("timeout"):            {},
	TransitionTrigger("budget_exhausted"):   {},
	TransitionTrigger("pattern_match"):      {},
}

var OriginDefaultBehaviors = map[OriginDefaultBehavior]struct{}{
	OriginDefaultBehavior("deny"):            {},
	OriginDefaultBehavior("minimal_profile"): {},
}

var OriginSpaceTypes = map[string]struct{}{
	"channel":      {},
	"group":        {},
	"dm":           {},
	"thread":       {},
	"issue":        {},
	"ticket":       {},
	"pull_request": {},
	"email_thread": {},
}

var OriginVisibilities = map[string]struct{}{
	"private":         {},
	"internal":        {},
	"public":          {},
	"external_shared": {},
}

var DetectionLevels = map[DetectionLevel]struct{}{
	DetectionLevel("safe"):       {},
	DetectionLevel("suspicious"): {},
	DetectionLevel("high"):       {},
	DetectionLevel("critical"):   {},
}

var Classifications = map[Classification]struct{}{
	Classification("public"):       {},
	Classification("internal"):     {},
	Classification("confidential"): {},
	Classification("restricted"):   {},
}

var LifecycleStates = map[LifecycleState]struct{}{
	LifecycleState("draft"):      {},
	LifecycleState("review"):     {},
	LifecycleState("approved"):   {},
	LifecycleState("deployed"):   {},
	LifecycleState("deprecated"): {},
	LifecycleState("archived"):   {},
}
